#!/bin/bash
# setup_udp_optimization.sh — Real-time UDP / ROS 2 NIC Optimization
#
# 실시간 UDP/ROS2(DDS) 통신을 위한 NIC 및 커널 네트워크 스택 최적화.
# IRQ affinity와 함께 사용하면 ControlLoop() jitter를 최소화할 수 있습니다.
#
# Usage:
#   sudo ./setup_udp_optimization.sh           # NIC 자동 감지
#   sudo ./setup_udp_optimization.sh enp1s0    # NIC 이름 명시
#
# 실행 시점: 부팅 후, ROS2 실행 전 (setup_irq_affinity.sh 이후 권장)
#
# 검증:
#   ethtool -c <NIC>   # coalescing 설정 확인
#   ethtool -k <NIC>   # offload 설정 확인
#   sysctl net.core.rmem_max   # 커널 버퍼 크기 확인

set -euo pipefail

# ── Colors ────────────────────────────────────────────────────────────────────
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
BLUE='\033[0;34m'
NC='\033[0m'

info()    { echo -e "${GREEN}[UDP-OPT]${NC} $*"; }
warn()    { echo -e "${YELLOW}[UDP-OPT]${NC} $*"; }
error()   { echo -e "${RED}[UDP-OPT]${NC} $*" >&2; exit 1; }
section() { echo -e "${BLUE}[UDP-OPT]${NC} $*"; }

# ── Root check ────────────────────────────────────────────────────────────────
if [[ "$EUID" -ne 0 ]]; then
  error "Root privileges required. Run: sudo $0 ${1:-}"
fi

# ── Helper: detect physical NIC ──────────────────────────────────────────────
# /sys/class/net/<iface>/device 심볼릭 링크는 물리 NIC에만 존재한다.
# 가상 인터페이스(docker0, veth*, br-* 등)를 자동으로 제외한다.
detect_physical_nic() {
  local iface
  for iface in /sys/class/net/*/; do
    iface=$(basename "$iface")
    [[ "$iface" == "lo" ]] && continue
    [[ -e "/sys/class/net/${iface}/device" ]] || continue
    if ip link show "$iface" 2>/dev/null | grep -q 'state UP'; then
      echo "$iface"
      return
    fi
  done
  for iface in /sys/class/net/*/; do
    iface=$(basename "$iface")
    [[ "$iface" == "lo" ]] && continue
    [[ -e "/sys/class/net/${iface}/device" ]] || continue
    echo "$iface"
    return
  done
}

# ── Detect or use specified NIC ───────────────────────────────────────────────
NIC="${1:-}"
if [[ -z "$NIC" ]]; then
  NIC=$(detect_physical_nic)
  [[ -z "$NIC" ]] && error "No physical network interface found. Specify one: sudo $0 <NIC>"
  warn "Auto-detected physical NIC: ${NIC}  (specify explicitly if wrong: sudo $0 <NIC>)"
fi

if ! ip link show "$NIC" &>/dev/null; then
  error "Interface '${NIC}' not found. Check with: ip link show"
fi

echo ""
info "Optimizing ${NIC} for Real-time UDP / ROS 2 (DDS)..."
echo ""

# ── ethtool 존재 확인 ─────────────────────────────────────────────────────────
if ! command -v ethtool &>/dev/null; then
  error "ethtool not found. Install with: sudo apt-get install -y ethtool"
fi

# ── Helper: best-effort ethtool (일부 NIC는 특정 설정을 지원하지 않을 수 있음) ──
run_ethtool() {
  if ethtool "$@" 2>/dev/null; then
    return 0
  else
    warn "  ethtool $* — not supported by this NIC (skipping)"
    return 0
  fi
}

# ── 1. NIC Interrupt Coalescing 비활성화 ──────────────────────────────────────
# 데이터가 찰 때까지 기다리지 않고 즉시 인터럽트를 발생시켜 지연 시간을 최소화합니다.
section "Step 1: Disabling NIC Interrupt Coalescing..."
run_ethtool -C "$NIC" rx-usecs 0 tx-usecs 0
run_ethtool -C "$NIC" adaptive-rx off adaptive-tx off
info "  Interrupt coalescing: rx-usecs=0, tx-usecs=0, adaptive=off"

# ── 2. 오프로딩 기능 비활성화 ────────────────────────────────────────────────
# 하드웨어가 패킷을 병합(Aggregation)하는 기능을 끄면 CPU 부하가 약간 늘지만
# 지연 시간은 줄어듭니다 (DDS RTPS 소형 패킷에 유리).
section "Step 2: Disabling NIC Offload Features..."
run_ethtool -K "$NIC" gro off lro off tso off gso off
info "  Offloads disabled: GRO, LRO, TSO, GSO"

# ── 3. 링 버퍼 크기 조정 ──────────────────────────────────────────────────────
# 너무 크면 지연 시간(버퍼링)이 늘고, 너무 작으면 패킷 유실이 발생합니다.
# 1024는 RT/DDS 통신에서 균형 잡힌 값입니다.
section "Step 3: Adjusting Ring Buffer Size (rx=1024, tx=1024)..."
run_ethtool -G "$NIC" rx 1024 tx 1024
info "  Ring buffer: rx=1024, tx=1024"

# ── 4. 커널 네트워크 스택 최적화 (sysctl) ────────────────────────────────────
# ROS 2 (DDS) 통신 시 대용량 데이터 전송 및 빠른 처리를 위한 설정.
# 영구 적용: /etc/sysctl.d/99-ros2-udp.conf
section "Step 4: Optimizing Kernel Network Stack (sysctl)..."

SYSCTL_CONF="/etc/sysctl.d/99-ros2-udp.conf"
if [[ -f "$SYSCTL_CONF" ]]; then
  cp "$SYSCTL_CONF" "${SYSCTL_CONF}.bak.$(date +%Y%m%d%H%M%S)"
  info "  Existing config backed up: ${SYSCTL_CONF}.bak.*"
fi
cat > "$SYSCTL_CONF" << 'EOF'
# ROS 2 / DDS Real-time UDP optimization
# Generated by setup_udp_optimization.sh
# Reference: https://docs.ros.org/en/jazzy/How-To-Guides/DDS-tuning.html

# UDP socket receive/send buffer: 2 GB
# CycloneDDS/FastDDS may need large buffers for high-bandwidth topics.
net.core.rmem_max     = 2147483647
net.core.rmem_default = 2147483647
net.core.wmem_max     = 2147483647
net.core.wmem_default = 2147483647

# Input packet queue depth — prevents drops under burst load
net.core.netdev_max_backlog = 5000
EOF

# 즉시 적용 (재부팅 없이)
sysctl -p "$SYSCTL_CONF" > /dev/null 2>&1 || {
  # sysctl -p <file> fails on some older distros; fall back to -w per param
  sysctl -w net.core.rmem_max=2147483647     > /dev/null
  sysctl -w net.core.rmem_default=2147483647 > /dev/null
  sysctl -w net.core.wmem_max=2147483647     > /dev/null
  sysctl -w net.core.wmem_default=2147483647 > /dev/null
  sysctl -w net.core.netdev_max_backlog=5000 > /dev/null
}

info "  rmem_max / wmem_max = 2147483647 (2 GB)"
info "  netdev_max_backlog  = 5000"
info "  Persistent config written to ${SYSCTL_CONF}"

# ── 5. IRQ 친화성 안내 ────────────────────────────────────────────────────────
# NIC IRQ affinity는 setup_irq_affinity.sh에서 별도 처리합니다.
# install.sh에서 두 스크립트를 순서대로 실행하면 최대 효과를 얻을 수 있습니다.
echo ""
info "Note: NIC IRQ affinity is managed by setup_irq_affinity.sh (run separately)."
info "      For best results, run both scripts together via install.sh."

echo ""
info "UDP optimization complete."
info ""
info "To verify settings:"
info "  ethtool -c ${NIC}        # coalescing (rx-usecs should be 0)"
info "  ethtool -k ${NIC}        # offloads   (gro, lro, tso, gso should be off)"
info "  ethtool -g ${NIC}        # ring buffer (rx/tx should be 1024)"
info "  sysctl net.core.rmem_max # should be 2147483647"
info ""
info "Settings persist across reboots via ${SYSCTL_CONF}."
info "NIC ethtool settings (coalescing, offload, ring) reset on reboot."
info "To make persistent, add to /etc/rc.local or a systemd oneshot service:"
info "  sudo $(realpath "$0") ${NIC}"
