// ── Offline batch judge for the S3.5a catchability map ──────────────────────
// dynamic_catching plan §11. The map is generated by a python tool (grid,
// ballistic flight, aggregation, plots) but the VERDICT has to come from the
// very function the runtime planner will call, with the very YAML keys it will
// read (S1.9, "같은 함수·같은 YAML 키"). Re-deriving the judgement in python
// would make the map describe a different system than the one that flies.
//
// So the split is: python owns everything that is not the judgement, and calls
// this over CSV. What lives here is only the batch plumbing — candidate I/O and
// the loop — so that the CLI's `main` holds no logic that a test cannot reach.
// `CatchPoseIk::Solve` itself is untouched.
//
// Frames: `p_c` and `v_ball` are in MODEL WORLD coordinates, exactly as
// `Solve` documents (Q2 — any base→world transform is the caller's job, and
// for one of the shipped arms the two candidates for "the base frame" differ by
// a 180° turn about z, which is silently plausible if confused; plan §11).
#pragma once

#include "rtc_controllers/catching/catch_pose_ik.hpp"
#include "rtc_urdf_bridge/rt_model_handle.hpp"

#include <Eigen/Core>

#include <cstdint>
#include <iosfwd>
#include <map>
#include <string>
#include <string_view>
#include <vector>

namespace rtc::catching {

/// One candidate catch instant: where the ball will be and how fast it is going.
struct BatchCandidate {
  std::int64_t id{0};  ///< caller's row id, echoed back so python can join
  int seed_id{0};      ///< which seed (wait-pose candidate) to start the IK from
  Eigen::Vector3d p_c{Eigen::Vector3d::Zero()};     ///< model world [m]
  Eigen::Vector3d v_ball{Eigen::Vector3d::Zero()};  ///< model world [m/s]
};

struct BatchRow {
  BatchCandidate candidate{};
  CatchPoseIkResult result{};
};

/// Stable snake_case name of a rejection reason, for the CSV and the map's
/// reason histogram. Total over the enum: a new reason breaks the build here
/// rather than silently becoming "unknown" in a distribution plot.
[[nodiscard]] std::string_view CatchPoseReasonName(CatchPoseReason reason) noexcept;

/// Read candidates from `id,seed_id,p_c_x,p_c_y,p_c_z,v_x,v_y,v_z`.
///
/// A header line is required and column ORDER IS TAKEN FROM IT, not assumed:
/// silently swapping p_c and v would still solve and still produce a map.
/// `seed_id` may be omitted (defaults to 0); every other column is mandatory.
/// Blank lines and `#` comments are skipped. Throws `std::invalid_argument`
/// naming the line number on anything else, including a non-finite value.
[[nodiscard]] std::vector<BatchCandidate> ParseCandidateCsv(std::istream& in);

/// Read seeds from `seed_id,q0,q1,...`. Every row must have the same width.
/// Throws `std::invalid_argument` on a duplicate id or a ragged row.
[[nodiscard]] std::map<int, Eigen::VectorXd> ParseSeedCsv(std::istream& in);

/// CSV header matching `BatchCsvRow`, with `nv` trailing `q<i>` columns.
[[nodiscard]] std::string BatchCsvHeader(int nv);

/// One result row. Doubles are written with enough digits to round-trip
/// exactly, so the map's numbers are the solver's numbers and not a rendering
/// of them. `q*` columns are written only for the reasons that leave a pose
/// (see `CatchPoseIkResult::q`); otherwise they are empty.
[[nodiscard]] std::string BatchCsvRow(const BatchRow& row);

/// Solve every candidate, in the given order.
///
/// Each candidate is an independent cold start from its own seed, so the output
/// for a candidate does not depend on what ran before it — the batch is a pure
/// function of the candidate set, which is what lets python shard it.
///
/// @param model      arm sub-model handle; mutated (its Data holds the FK).
/// @param catch_frame frame id in `model`.
/// @param candidates rows to judge.
/// @param seeds      seed_id → q_seed, each with `model.nv()` entries.
/// @param opt        tuning, from `ParseCatchPoseIkParams`.
/// @throws std::invalid_argument if a candidate names a seed that is absent or
///         a seed has the wrong size — failing closed beats judging a whole
///         map against a silently substituted posture.
[[nodiscard]] std::vector<BatchRow> RunBatch(rtc_urdf_bridge::RtModelHandle& model,
                                             pinocchio::FrameIndex catch_frame,
                                             const std::vector<BatchCandidate>& candidates,
                                             const std::map<int, Eigen::VectorXd>& seeds,
                                             const CatchPoseIkOptions& opt);

}  // namespace rtc::catching
