#!/bin/bash
# install_rt.sh — RT system setup helpers for install.sh
#
# 제공 함수:
#   run_setup_script DESC SCRIPT_BASENAME [ARGS...]
#       repo_scripts/scripts/<SCRIPT_BASENAME> 을 sudo bash 로 실행하는
#       공통 wrapper. 7개 setup_* 함수가 같은 패턴을 공유한다.
#   install_rt_permissions   — /etc/security/limits.conf @realtime 그룹
#   setup_rt_sudoers         — /etc/sudoers.d/ur5e-rt-controller
#   install_cset_tools       — apt: cpuset / python3-cpuset
#   setup_rt_kernel_params   — setup_grub_rt.sh wrapper
#   setup_irq_affinity       — setup_irq_affinity.sh wrapper
#   setup_udp_optimization   — setup_udp_optimization.sh wrapper
#   setup_nvidia_rt          — NVIDIA GPU 감지 + setup_nvidia_rt.sh wrapper
#   setup_cpu_governor       — 비-NVIDIA 시스템용 wrapper
#
# Caller scope 의존:
#   INSTALL_SCRIPT_DIR, WORKSPACE, USER (env), 로거 (info/warn/success/error)

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
  echo "ERROR: This file should be sourced, not executed." >&2
  exit 1
fi

[[ -n "${_INSTALL_RT_LOADED:-}" ]] && return 0
_INSTALL_RT_LOADED=1

# ── 공통 wrapper ────────────────────────────────────────────────────────────
# Usage: run_setup_script "Description" "script_basename.sh" [extra args...]
# 동작:
#   1) repo_scripts/scripts/<basename> 존재 확인 (없으면 warn + return 0)
#   2) info "Description..." → sudo bash <script> [args] 실행
#   3) 성공 시 success, 실패 시 warn (install.sh 흐름은 계속)
# 반환: 0 (스크립트 실패 시도 caller 종료를 막기 위해 항상 0)
run_setup_script() {
  local desc="$1"
  local basename="$2"
  shift 2

  local script="${INSTALL_SCRIPT_DIR}/repo_scripts/scripts/${basename}"

  if [[ ! -f "$script" ]]; then
    warn "${basename} not found — skipping ${desc,,}"
    warn "Run manually: sudo ${script} [args]"
    return 0
  fi

  info "${desc}..."
  if sudo bash "$script" "$@"; then
    success "${desc} complete"
  else
    warn "${desc} failed — continuing without it"
    warn "Run manually: sudo ${script} [args]"
  fi
  return 0
}

# ── RT permissions (robot + full) ──────────────────────────────────────────────
install_rt_permissions() {
  info "Configuring RT scheduling permissions..."
  sudo groupadd -f realtime
  sudo usermod -aG realtime "$USER"

  if ! grep -q "@realtime.*rtprio" /etc/security/limits.conf; then
    echo "@realtime - rtprio 99" | sudo tee -a /etc/security/limits.conf > /dev/null
  fi
  # memlock unlimited 설정 (이미 올바르면 건너뜀)
  if ! grep -q '^@realtime - memlock unlimited$' /etc/security/limits.conf 2>/dev/null; then
    sudo sed -i '/@realtime.*memlock/d' /etc/security/limits.conf
    echo "@realtime - memlock unlimited" | sudo tee -a /etc/security/limits.conf > /dev/null
  fi

  success "RT permissions configured (rtprio=99, memlock=unlimited)"
  warn "IMPORTANT: Log out and log back in for RT permissions to take effect"
  warn "Verify with: ulimit -l  (MUST be 'unlimited' to avoid RMW load errors with mlockall)"
}

# ── Passwordless sudo for RT scripts (robot + full) ────────────────────────
# cpu_shield.sh는 launch 파일에서 비대화형으로 sudo 호출되므로
# 비밀번호 없이 실행 가능하도록 sudoers drop-in 파일을 설정한다.
setup_rt_sudoers() {
  info "Configuring passwordless sudo for RT scripts..."

  local SUDOERS_FILE="/etc/sudoers.d/ur5e-rt-controller"

  # 설치된 cpu_shield.sh 경로 — repo_scripts/CMakeLists.txt 가 install (PROGRAMS) 로
  # DESTINATION lib/${PROJECT_NAME} 에 박는다. 2026-04-30 패키지 rename
  # (rtc_scripts → repo_scripts) 이후 경로는 install/repo_scripts/lib/repo_scripts/.
  local INSTALLED_SHIELD="${WORKSPACE}/install/repo_scripts/lib/repo_scripts/cpu_shield.sh"
  # 소스 cpu_shield.sh 경로
  local SOURCE_SHIELD="${INSTALL_SCRIPT_DIR}/repo_scripts/scripts/cpu_shield.sh"

  # cset 명령 경로
  local CSET_PATH
  CSET_PATH="$(command -v cset 2>/dev/null || echo "/usr/bin/cset")"

  local SUDOERS_CONTENT
  SUDOERS_CONTENT="# RTC (Real-Time Controller) — passwordless sudo for CPU shield management
# Generated by install.sh — do not edit manually
# cpu_shield.sh: launch 파일에서 비대화형 sudo 호출에 필요
%realtime ALL=(ALL) NOPASSWD: ${INSTALLED_SHIELD} *
%realtime ALL=(ALL) NOPASSWD: ${SOURCE_SHIELD} *
%realtime ALL=(ALL) NOPASSWD: ${CSET_PATH} shield *"

  # 기존 파일과 동일하면 건너뜀
  if [[ -f "$SUDOERS_FILE" ]] && echo "$SUDOERS_CONTENT" | diff -q - "$SUDOERS_FILE" &>/dev/null; then
    success "RT sudoers already configured"
    return
  fi

  # sudoers 파일 생성 (visudo로 문법 검증)
  local TEMP_SUDOERS
  TEMP_SUDOERS=$(mktemp)
  echo "$SUDOERS_CONTENT" > "$TEMP_SUDOERS"
  chmod 0440 "$TEMP_SUDOERS"

  if sudo visudo -cf "$TEMP_SUDOERS" &>/dev/null; then
    sudo cp "$TEMP_SUDOERS" "$SUDOERS_FILE"
    sudo chmod 0440 "$SUDOERS_FILE"
    rm -f "$TEMP_SUDOERS"
    success "Passwordless sudo configured for cpu_shield.sh"
    info "  Sudoers file: $SUDOERS_FILE"
  else
    rm -f "$TEMP_SUDOERS"
    warn "Sudoers syntax check failed — skipping"
    warn "Run manually: sudo visudo -f $SUDOERS_FILE"
  fi
}

# ── cpuset tools for dynamic CPU isolation ──────────────────────────────────
# cset shield 명령을 사용하여 런타임에 CPU 격리를 on/off 할 수 있다.
# isolcpus GRUB 파라미터 없이도 빌드 시 전체 코어, 실행 시 격리 코어를 사용.
install_cset_tools() {
  info "Installing cpuset tools for dynamic CPU isolation..."
  if command -v cset &>/dev/null; then
    success "cset already installed"
    return
  fi
  if sudo apt-get install -y cpuset > /dev/null 2>&1; then
    success "cset installed via cpuset package"
  elif sudo apt-get install -y python3-cpuset > /dev/null 2>&1; then
    success "cset installed via python3-cpuset"
  else
    warn "cset 설치 실패 — /sys/fs/cgroup/cpuset fallback 사용"
    warn "수동 설치: sudo apt-get install -y cpuset"
  fi
}

# ── [RT] GRUB 커널 파라미터 + sysctl (NVIDIA 무관, robot + full) ──────────────
# clocksource=tsc, nmi_watchdog=0, sched_rt_runtime_us=-1 등 RT 필수 설정.
# NVIDIA 시스템은 setup_nvidia_rt.sh [3/11]에서도 같은 GRUB 파라미터를 설정하지만,
# "이미 존재" 로 건너뛰므로 중복 문제는 없다.
setup_rt_kernel_params() {
  run_setup_script "Configuring GRUB RT kernel parameters" "setup_grub_rt.sh"
}

# ── [방안 D] NIC IRQ affinity (robot + full) ────────────────────────────────
# RT 코어를 NIC 인터럽트로부터 보호.
# 모든 하드웨어 IRQ를 OS 코어로 제한한다.
# CPU 레이아웃 계산은 setup_irq_affinity.sh 내부에서 rt_common.sh로 처리.
setup_irq_affinity() {
  local script="${INSTALL_SCRIPT_DIR}/repo_scripts/scripts/setup_irq_affinity.sh"
  if run_setup_script "Configuring NIC IRQ affinity" "setup_irq_affinity.sh"; then
    # 추가 안내 (다른 wrapper와 달리 reboot persistence 안내가 필요)
    if [[ -f "$script" ]]; then
      warn "NOTE: IRQ affinity resets on reboot. To make permanent:"
      warn "  Add 'sudo $script' to /etc/rc.local or a systemd oneshot service"
    fi
  fi
}

# ── [UDP/DDS] NIC & kernel network stack optimization (robot + full) ──────────
setup_udp_optimization() {
  local script="${INSTALL_SCRIPT_DIR}/repo_scripts/scripts/setup_udp_optimization.sh"
  if run_setup_script "Configuring NIC & kernel network stack for real-time UDP/DDS" \
                      "setup_udp_optimization.sh"; then
    if [[ -f "$script" ]]; then
      warn "NOTE: sysctl settings persist via /etc/sysctl.d/99-ros2-udp.conf"
      warn "NOTE: ethtool NIC settings (coalescing, offload, ring) reset on reboot."
      warn "  To make permanent: add 'sudo $script' to /etc/rc.local or a systemd service"
    fi
  fi
}

# ── [NVIDIA] RT-safe GPU configuration (robot + full) ────────────────────────
# NVIDIA GPU가 감지되면 RT 커널 호환성 + 화면 티어링 방지를 설정한다.
setup_nvidia_rt() {
  # NVIDIA GPU 존재 여부 확인 (wrapper 호출 전 분기)
  if ! lspci 2>/dev/null | grep -qi 'nvidia'; then
    info "No NVIDIA GPU detected — skipping NVIDIA RT setup"
    return
  fi

  info "NVIDIA GPU detected — configuring RT-safe GPU settings (11 steps)..."
  info "  Includes: modprobe, GRUB, IRQ affinity, persistence, nouveau blacklist,"
  info "            X11 anti-tearing, compositor boost, DKMS RT build, CPU governor"
  if run_setup_script "NVIDIA RT setup" "setup_nvidia_rt.sh"; then
    warn "NOTE: A reboot is required for GRUB and X11 changes to take effect"
  fi
}

# ── CPU Governor → performance (비-NVIDIA 시스템용) ───────────────────────────
# NVIDIA GPU가 있는 시스템은 setup_nvidia_rt.sh [10/11]에서 처리.
# NVIDIA가 없는 시스템에서도 powersave → performance 전환이 필요하다.
setup_cpu_governor() {
  # NVIDIA GPU가 있는 시스템은 setup_nvidia_rt.sh에서 호출됨 (분기는 wrapper 호출 전)
  if lspci 2>/dev/null | grep -qi 'nvidia'; then
    return
  fi
  run_setup_script "Setting CPU governor to performance" "setup_cpu_governor.sh"
}
