#!/usr/bin/env bash
# AUTO-GENERATED by repo_scripts/scripts/gen_thread_layout.py -- DO NOT EDIT.
# Source of truth: repo_scripts/config/thread_layout.yaml
# Regenerate:      python3 repo_scripts/scripts/gen_thread_layout.py --write
# Drift gate:      python3 repo_scripts/scripts/gen_thread_layout.py --check
#
# Sourced by repo_scripts/scripts/lib/rt_common.sh. Everything here is a pure
# function of the physical core count -- no sysfs, no build artifacts -- so
# install.sh can source it before the workspace is built (bootstrap order).
#
# Every slot below is a ThreadConfig::cpu_core *slot index*, NOT a kernel
# logical CPU id. Run it through slot_to_logical_cpu() before comparing
# against a /proc affinity mask.
# shellcheck shell=bash

RTC_THREAD_LAYOUT_VERSION="v4.1"

# Tier id for a physical core count. Mirrors
# SelectThreadConfigsForCoreCount() in thread_config_generated.hpp.
_rtc_layout_tier() {
  local ncpu="$1"
  if [[ "$ncpu" -ge 16 ]]; then
    echo 16
  elif [[ "$ncpu" -ge 14 ]]; then
    echo 14
  elif [[ "$ncpu" -ge 12 ]]; then
    echo 12
  elif [[ "$ncpu" -ge 10 ]]; then
    echo 10
  elif [[ "$ncpu" -ge 8 ]]; then
    echo 8
  elif [[ "$ncpu" -ge 6 ]]; then
    echo 6
  else
    echo 4
  fi
}

# get_role_spec <role> [ncpu] -> "<slot> <policy> <priority> <nice>"
# Returns non-zero for a role that does not exist on the tier (e.g. an
# mpc_worker below the 10-core tier).
get_role_spec() {
  local role="$1"
  local ncpu="${2:-$(get_physical_cores)}"
  local tier
  tier=$(_rtc_layout_tier "$ncpu")
  case "${tier}|${role}" in
    "4|rt_control") echo "1 SCHED_FIFO 90 0" ;;
    "4|rt_callback") echo "2 SCHED_FIFO 70 0" ;;
    "4|mpc_main") echo "3 SCHED_OTHER 0 -5" ;;
    "4|arm_driver") echo "0 SCHED_OTHER 0 0" ;;
    "4|hand_driver") echo "0 SCHED_OTHER 0 0" ;;
    "4|nrt_callback") echo "0 SCHED_OTHER 0 0" ;;
    "4|nrt_publish") echo "0 SCHED_OTHER 0 0" ;;
    "4|nrt_logging") echo "0 SCHED_OTHER 0 -5" ;;
    "4|sim_thread") echo "-1 SCHED_OTHER 0 0" ;;
    "4|viewer") echo "-1 SCHED_OTHER 0 0" ;;
    "6|rt_control") echo "1 SCHED_FIFO 90 0" ;;
    "6|rt_callback") echo "2 SCHED_FIFO 70 0" ;;
    "6|mpc_main") echo "3 SCHED_FIFO 60 0" ;;
    "6|arm_driver") echo "4 SCHED_OTHER 0 0" ;;
    "6|hand_driver") echo "4 SCHED_OTHER 0 0" ;;
    "6|nrt_callback") echo "5 SCHED_OTHER 0 0" ;;
    "6|nrt_publish") echo "5 SCHED_OTHER 0 0" ;;
    "6|nrt_logging") echo "5 SCHED_OTHER 0 -5" ;;
    "6|sim_thread") echo "-1 SCHED_OTHER 0 0" ;;
    "6|viewer") echo "-1 SCHED_OTHER 0 0" ;;
    "8|rt_control") echo "1 SCHED_FIFO 90 0" ;;
    "8|rt_callback") echo "2 SCHED_FIFO 70 0" ;;
    "8|mpc_main") echo "3 SCHED_FIFO 60 0" ;;
    "8|arm_driver") echo "4 SCHED_OTHER 0 0" ;;
    "8|hand_driver") echo "5 SCHED_OTHER 0 0" ;;
    "8|nrt_callback") echo "7 SCHED_OTHER 0 0" ;;
    "8|nrt_publish") echo "7 SCHED_OTHER 0 0" ;;
    "8|nrt_logging") echo "6 SCHED_OTHER 0 -5" ;;
    "8|sim_thread") echo "-1 SCHED_OTHER 0 0" ;;
    "8|viewer") echo "-1 SCHED_OTHER 0 0" ;;
    "10|rt_control") echo "1 SCHED_FIFO 90 0" ;;
    "10|rt_callback") echo "2 SCHED_FIFO 70 0" ;;
    "10|mpc_main") echo "3 SCHED_FIFO 60 0" ;;
    "10|mpc_worker_0") echo "4 SCHED_FIFO 55 0" ;;
    "10|arm_driver") echo "5 SCHED_OTHER 0 0" ;;
    "10|hand_driver") echo "6 SCHED_OTHER 0 0" ;;
    "10|nrt_callback") echo "8 SCHED_OTHER 0 0" ;;
    "10|nrt_publish") echo "8 SCHED_OTHER 0 0" ;;
    "10|nrt_logging") echo "7 SCHED_OTHER 0 -5" ;;
    "10|sim_thread") echo "-1 SCHED_OTHER 0 0" ;;
    "10|viewer") echo "-1 SCHED_OTHER 0 0" ;;
    "12|rt_control") echo "1 SCHED_FIFO 90 0" ;;
    "12|rt_callback") echo "2 SCHED_FIFO 70 0" ;;
    "12|mpc_main") echo "3 SCHED_FIFO 60 0" ;;
    "12|mpc_worker_0") echo "4 SCHED_FIFO 55 0" ;;
    "12|mpc_worker_1") echo "5 SCHED_FIFO 55 0" ;;
    "12|arm_driver") echo "6 SCHED_OTHER 0 0" ;;
    "12|hand_driver") echo "7 SCHED_OTHER 0 0" ;;
    "12|nrt_callback") echo "9 SCHED_OTHER 0 0" ;;
    "12|nrt_publish") echo "9 SCHED_OTHER 0 0" ;;
    "12|nrt_logging") echo "8 SCHED_OTHER 0 -5" ;;
    "12|sim_thread") echo "-1 SCHED_OTHER 0 0" ;;
    "12|viewer") echo "-1 SCHED_OTHER 0 0" ;;
    "14|rt_control") echo "1 SCHED_FIFO 90 0" ;;
    "14|rt_callback") echo "2 SCHED_FIFO 70 0" ;;
    "14|mpc_main") echo "3 SCHED_FIFO 60 0" ;;
    "14|mpc_worker_0") echo "4 SCHED_FIFO 55 0" ;;
    "14|mpc_worker_1") echo "5 SCHED_FIFO 55 0" ;;
    "14|arm_driver") echo "6 SCHED_OTHER 0 0" ;;
    "14|hand_driver") echo "7 SCHED_OTHER 0 0" ;;
    "14|nrt_callback") echo "9 SCHED_OTHER 0 0" ;;
    "14|nrt_publish") echo "9 SCHED_OTHER 0 0" ;;
    "14|nrt_logging") echo "8 SCHED_OTHER 0 -5" ;;
    "14|sim_thread") echo "-1 SCHED_OTHER 0 0" ;;
    "14|viewer") echo "-1 SCHED_OTHER 0 0" ;;
    "16|rt_control") echo "1 SCHED_FIFO 90 0" ;;
    "16|rt_callback") echo "2 SCHED_FIFO 70 0" ;;
    "16|mpc_main") echo "3 SCHED_FIFO 60 0" ;;
    "16|mpc_worker_0") echo "4 SCHED_FIFO 55 0" ;;
    "16|mpc_worker_1") echo "5 SCHED_FIFO 55 0" ;;
    "16|arm_driver") echo "6 SCHED_OTHER 0 0" ;;
    "16|hand_driver") echo "7 SCHED_OTHER 0 0" ;;
    "16|nrt_callback") echo "9 SCHED_OTHER 0 0" ;;
    "16|nrt_publish") echo "9 SCHED_OTHER 0 0" ;;
    "16|nrt_logging") echo "8 SCHED_OTHER 0 -5" ;;
    "16|sim_thread") echo "-1 SCHED_OTHER 0 0" ;;
    "16|viewer") echo "-1 SCHED_OTHER 0 0" ;;
    *) return 1 ;;
  esac
}

get_role_slot() {
  local spec
  spec=$(get_role_spec "$@") || return 1
  echo "$spec" | cut -d" " -f1
}

get_role_policy() {
  local spec
  spec=$(get_role_spec "$@") || return 1
  echo "$spec" | cut -d" " -f2
}

get_role_priority() {
  local spec
  spec=$(get_role_spec "$@") || return 1
  echo "$spec" | cut -d" " -f3
}

get_role_nice() {
  local spec
  spec=$(get_role_spec "$@") || return 1
  echo "$spec" | cut -d" " -f4
}

# MPC slots (main first, then workers) as CSV. $1 overrides the detected
# physical core count so print_thread_layout and the tests can render a
# tier this machine does not have.
get_mpc_cores() {
  local ncpu="${1:-$(get_physical_cores)}"
  local tier
  tier=$(_rtc_layout_tier "$ncpu")
  case "$tier" in
    4) echo "3" ;;
    6) echo "3" ;;
    8) echo "3" ;;
    10) echo "3,4" ;;
    12) echo "3,4,5" ;;
    14) echo "3,4,5" ;;
    16) echo "3,4,5" ;;
  esac
}

# RT group slots: rt_control + rt_callback + MPC (main + workers).
# Base for get_rt_cores_with_siblings() / get_cm_shield_cpus().
get_rt_cores() {
  local ncpu="${1:-$(get_physical_cores)}"
  local tier
  tier=$(_rtc_layout_tier "$ncpu")
  case "$tier" in
    4) echo "1,2,3" ;;
    6) echo "1,2,3" ;;
    8) echo "1,2,3" ;;
    10) echo "1,2,3,4" ;;
    12) echo "1,2,3,4,5" ;;
    14) echo "1,2,3,4,5" ;;
    16) echo "1,2,3,4,5" ;;
  esac
}

# nrt_logging + nrt_callback slots, deduplicated and ascending. On the
# degraded tier both share the OS slot -- callers that shield must drop
# the OS slot (get_cm_shield_cpus does), never widen onto it.
get_nrt_cores() {
  local ncpu="${1:-$(get_physical_cores)}"
  local tier
  tier=$(_rtc_layout_tier "$ncpu")
  case "$tier" in
    4) echo "0" ;;
    6) echo "5" ;;
    8) echo "6,7" ;;
    10) echo "7,8" ;;
    12) echo "8,9" ;;
    14) echo "8,9" ;;
    16) echo "8,9" ;;
  esac
}

# Slot the external arm driver process belongs on (launch taskset target).
get_arm_driver_slot() {
  local ncpu="${1:-$(get_physical_cores)}"
  local tier
  tier=$(_rtc_layout_tier "$ncpu")
  case "$tier" in
    4) echo "0" ;;
    6) echo "4" ;;
    8) echo "4" ;;
    10) echo "5" ;;
    12) echo "6" ;;
    14) echo "6" ;;
    16) echo "6" ;;
  esac
}

# Slot the external hand driver process belongs on (in-process self-pin, #345).
get_hand_driver_slot() {
  local ncpu="${1:-$(get_physical_cores)}"
  local tier
  tier=$(_rtc_layout_tier "$ncpu")
  case "$tier" in
    4) echo "0" ;;
    6) echo "4" ;;
    8) echo "5" ;;
    10) echo "6" ;;
    12) echo "7" ;;
    14) echo "7" ;;
    16) echo "7" ;;
  esac
}

# OS / DDS / NIC IRQ slot. Never shielded, never an RT pin target.
get_os_cores() {
  echo "0"
}

# Expected in-process controller threads for verify_rt_runtime.sh, one
# "name:slot:policy:priority[:optional]" per line. policy: 1=SCHED_FIFO,
# 0=SCHED_OTHER. "optional" means a missing thread is SKIP, not WARN.
rtc_expected_threads() {
  local ncpu="${1:-$(get_physical_cores)}"
  local tier
  tier=$(_rtc_layout_tier "$ncpu")
  case "$tier" in
    4)
      echo "rt_control:1:1:90"
      echo "rt_callback:2:1:70"
      echo "mpc_main:3:0:0"
      echo "nrt_logging:0:0:0"
      echo "nrt_callback:0:0:0"
      echo "nrt_publish:0:0:0"
      ;;
    6)
      echo "rt_control:1:1:90"
      echo "rt_callback:2:1:70"
      echo "mpc_main:3:1:60"
      echo "nrt_logging:5:0:0"
      echo "nrt_callback:5:0:0"
      echo "nrt_publish:5:0:0"
      ;;
    8)
      echo "rt_control:1:1:90"
      echo "rt_callback:2:1:70"
      echo "mpc_main:3:1:60"
      echo "nrt_logging:6:0:0"
      echo "nrt_callback:7:0:0"
      echo "nrt_publish:7:0:0"
      ;;
    10)
      echo "rt_control:1:1:90"
      echo "rt_callback:2:1:70"
      echo "mpc_main:3:1:60"
      echo "mpc_worker_0:4:1:55:optional"
      echo "nrt_logging:7:0:0"
      echo "nrt_callback:8:0:0"
      echo "nrt_publish:8:0:0"
      ;;
    12)
      echo "rt_control:1:1:90"
      echo "rt_callback:2:1:70"
      echo "mpc_main:3:1:60"
      echo "mpc_worker_0:4:1:55:optional"
      echo "mpc_worker_1:5:1:55:optional"
      echo "nrt_logging:8:0:0"
      echo "nrt_callback:9:0:0"
      echo "nrt_publish:9:0:0"
      ;;
    14)
      echo "rt_control:1:1:90"
      echo "rt_callback:2:1:70"
      echo "mpc_main:3:1:60"
      echo "mpc_worker_0:4:1:55:optional"
      echo "mpc_worker_1:5:1:55:optional"
      echo "nrt_logging:8:0:0"
      echo "nrt_callback:9:0:0"
      echo "nrt_publish:9:0:0"
      ;;
    16)
      echo "rt_control:1:1:90"
      echo "rt_callback:2:1:70"
      echo "mpc_main:3:1:60"
      echo "mpc_worker_0:4:1:55:optional"
      echo "mpc_worker_1:5:1:55:optional"
      echo "nrt_logging:8:0:0"
      echo "nrt_callback:9:0:0"
      echo "nrt_publish:9:0:0"
      ;;
  esac
}

