#!/bin/bash
# setup_display_rt.sh — RT 커널 환경의 디스플레이/GUI 설정
#
# setup_nvidia_rt.sh의 Stage 7(X11 anti-tearing)과 Stage 8(compositor 우선순위
# 부스트)을 독립 스크립트로 분리한 것이다.
# NVIDIA GPU가 아닌 환경에서도 compositor 우선순위 부스트는 유효하다.
#
# 대상: Ubuntu 22.04 / 24.04, PREEMPT_RT 커널, X11 또는 Wayland 환경
# 제어 루프: 500Hz (2ms period), 목표 max jitter: < 200μs
#
# Usage:
#   sudo ./setup_display_rt.sh          # 전체 설정 적용
#   sudo ./setup_display_rt.sh --help   # 도움말
#
# 실행 시점: RT 커널 부팅 후, ROS2 실행 전 (1회 설정)
# 검증:
#   cat /etc/X11/xorg.conf.d/20-nvidia-antitear.conf  # X11 anti-tearing
#   systemctl status rt-compositor-boost               # compositor 부스트 서비스

set -euo pipefail

# ── 공통 라이브러리 로드 ────────────────────────────────────────────────────
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=lib/rt_common.sh
source "${SCRIPT_DIR}/lib/rt_common.sh"
make_logger "DISPLAY-RT"

# ── Root 권한 확인 ──────────────────────────────────────────────────────────
require_root "$@"

# ── Help ────────────────────────────────────────────────────────────────────
if [[ "${1:-}" == "--help" || "${1:-}" == "-h" ]]; then
  echo ""
  echo -e "${BOLD}setup_display_rt.sh — RT 커널 환경 디스플레이/GUI 설정${NC}"
  echo ""
  echo "Usage: sudo $0"
  echo ""
  echo "수행 작업:"
  echo "  1. X11 화면 티어링 방지 (ForceFullCompositionPipeline)"
  echo "     - /etc/X11/xorg.conf.d/20-nvidia-antitear.conf 생성"
  echo "     - MetaModes, TripleBuffer, AllowIndirectGLXProtocol 설정"
  echo "  2. Compositor 우선순위 부스트 서비스"
  echo "     - Xorg, Xwayland, gnome-shell, kwin 프로세스 renice -10"
  echo "     - systemd 서비스로 부팅 시 자동 적용"
  echo ""
  echo "참고:"
  echo "  - setup_nvidia_rt.sh Stage 7, 8에서 분리된 스크립트"
  echo "  - Wayland 환경에서는 XWayland 창에만 anti-tearing 적용"
  echo "  - headless 환경에서도 설정 파일은 설치 (GUI 시작 시 적용)"
  echo ""
  exit 0
fi

# ── Banner ──────────────────────────────────────────────────────────────────
echo ""
echo -e "${BOLD}${CYAN}╔═══════════════════════════════════════════════════════════╗${NC}"
echo -e "${BOLD}${CYAN}║     Display / GUI Settings for RT Kernel Environment      ║${NC}"
echo -e "${BOLD}${CYAN}║     Anti-Tearing + Compositor Priority Boost              ║${NC}"
echo -e "${BOLD}${CYAN}╚═══════════════════════════════════════════════════════════╝${NC}"
echo ""

# ── 디스플레이 서버 감지 ────────────────────────────────────────────────────
# Wayland, X11, headless 중 하나로 분류한다.
# headless 환경에서도 설정 파일은 설치하여 재부팅 후 GUI 시작 시 적용되도록 한다.
DISPLAY_SERVER="unknown"
if [[ -n "${WAYLAND_DISPLAY:-}" ]]; then
  DISPLAY_SERVER="wayland"
elif [[ -n "${DISPLAY:-}" ]]; then
  DISPLAY_SERVER="x11"
else
  DISPLAY_SERVER="headless"
fi
info "디스플레이 서버: ${DISPLAY_SERVER}"

# ══════════════════════════════════════════════════════════════════════════════
# [1/2] X11 Anti-Tearing Configuration (ForceFullCompositionPipeline)
# ══════════════════════════════════════════════════════════════════════════════
echo ""
echo -e "${BOLD}━━━ [1/2] X11 화면 티어링 방지 ━━━${NC}"
echo ""

# ForceFullCompositionPipeline은 NVIDIA 독점 드라이버의 vsync 기반 티어링 방지 기능.
# nvidia-drm modeset=1만으로는 KMS만 활성화될 뿐, 실제 티어링은 해결되지 않는다.
# Wayland 환경에서도 XWayland fallback 시 유효하므로, X11 설정 파일은 항상 설치한다.
XORG_CONF_DIR="/etc/X11/xorg.conf.d"
XORG_CONF="${XORG_CONF_DIR}/20-nvidia-antitear.conf"

# nvidia-settings에서 현재 연결된 디스플레이 이름 감지
DISPLAY_NAME=""
if command -v nvidia-settings &>/dev/null && [[ "$DISPLAY_SERVER" != "headless" ]]; then
  DISPLAY_NAME=$(nvidia-settings -q CurrentMetaMode -t 2>/dev/null \
    | grep -oP '^[A-Za-z]+-[0-9]+' | head -1 || true)
fi

# 디스플레이 이름 감지 결과에 따라 MetaMode 값 결정
if [[ -n "$DISPLAY_NAME" ]]; then
  METAMODE_VALUE="${DISPLAY_NAME}: nvidia-auto-select +0+0 {ForceFullCompositionPipeline=On}"
  info "감지된 디스플레이: ${DISPLAY_NAME}"
else
  METAMODE_VALUE="nvidia-auto-select +0+0 {ForceFullCompositionPipeline=On}"
  info "디스플레이 이름 미감지 — 범용 MetaMode 사용"
fi

# xorg.conf.d 설정 파일 내용 생성
# ForceFullCompositionPipeline: GPU 측 vsync 강제 (compositor 무관)
# TripleBuffer: 프레임 드롭 방지 (vsync 활성화 시 성능 보완)
XORG_CONTENT="# NVIDIA 화면 티어링 방지 설정
# Generated by setup_display_rt.sh
#
# ForceFullCompositionPipeline: GPU 측 vsync 강제 (compositor 무관)
# TripleBuffer: 프레임 드롭 방지 (vsync 활성화 시 성능 보완)
Section \"Screen\"
    Identifier     \"Screen0\"
    Device         \"Device0\"
    Monitor        \"Monitor0\"
    Option         \"MetaModes\" \"${METAMODE_VALUE}\"
    Option         \"TripleBuffer\" \"On\"
    Option         \"AllowIndirectGLXProtocol\" \"off\"
EndSection"

# 멱등성: 디렉토리 생성 후 기존 파일과 비교하여 동일하면 건너뜀
mkdir -p "$XORG_CONF_DIR"

if write_file_if_changed "$XORG_CONF" "$XORG_CONTENT"; then
  success "X11 anti-tearing 설정 완료: ${XORG_CONF}"
else
  info "이미 동일한 X11 설정이 존재합니다 — 건너뜀"
fi

# Wayland 환경 경고: 순수 Wayland 앱에는 적용되지 않음
if [[ "$DISPLAY_SERVER" == "wayland" ]]; then
  info "Wayland 환경 감지 — XWayland 창에만 적용됩니다"
  info "순수 Wayland 앱의 티어링은 compositor(Mutter/KWin) 설정을 확인하세요"
  warn "Wayland 환경 — ForceFullCompositionPipeline은 XWayland에만 적용"
fi

echo ""

# ══════════════════════════════════════════════════════════════════════════════
# [2/2] Compositor Priority Boost for RT Environment
# ══════════════════════════════════════════════════════════════════════════════
echo -e "${BOLD}━━━ [2/2] Compositor 우선순위 부스트 ━━━${NC}"
echo ""

# RT 커널에서 SCHED_FIFO 스레드(제어 루프)가 SCHED_OTHER(compositor)를 완전히 선점하면
# 화면 갱신이 밀려서 끊김이 발생한다.
# compositor의 nice 값을 낮춰(우선순위 높임) SCHED_OTHER 내에서 최우선으로 실행되게 한다.
# 주의: SCHED_FIFO로 올리면 RT 제어 루프와 경쟁하므로 nice 조정만 수행.
COMPOSITOR_SERVICE="/etc/systemd/system/rt-compositor-boost.service"
COMPOSITOR_SCRIPT="/usr/local/bin/rt-compositor-boost.sh"

# ── compositor 부스트 스크립트 생성 ──────────────────────────────────────────
# Xorg, Xwayland, gnome-shell, kwin 프로세스를 찾아 renice -10 적용
COMPOSITOR_SCRIPT_CONTENT='#!/bin/bash
# rt-compositor-boost.sh — RT 환경에서 compositor/Xorg 우선순위 부스트
# Generated by setup_display_rt.sh
#
# RT 스레드(SCHED_FIFO)에 의해 디스플레이 compositor가 기아 상태에 빠지는 것을 방지.
# SCHED_OTHER 내에서 nice -10으로 우선순위를 높인다.
set -euo pipefail

BOOSTED=0

# Xorg / Xwayland
for proc_name in Xorg Xwayland; do
  for pid in $(pgrep -x "$proc_name" 2>/dev/null || true); do
    renice -n -10 -p "$pid" 2>/dev/null && ((BOOSTED++)) || true
  done
done

# GNOME compositor (mutter)
for pid in $(pgrep -f "gnome-shell" 2>/dev/null || true); do
  renice -n -10 -p "$pid" 2>/dev/null && ((BOOSTED++)) || true
done

# KDE compositor (kwin)
for pid in $(pgrep -f "kwin" 2>/dev/null || true); do
  renice -n -10 -p "$pid" 2>/dev/null && ((BOOSTED++)) || true
done

echo "rt-compositor-boost: boosted ${BOOSTED} display processes (nice -10)"'

# ── systemd 서비스 유닛 내용 ────────────────────────────────────────────────
# display-manager.service 및 graphical.target 이후에 실행되도록 의존성 설정.
# ExecStartPre=/bin/sleep 5 — 디스플레이 매니저가 완전히 시작된 후 실행.
COMPOSITOR_SERVICE_CONTENT="[Unit]
Description=Boost compositor/Xorg priority for RT kernel display stability
After=display-manager.service
After=graphical.target

[Service]
Type=oneshot
ExecStart=${COMPOSITOR_SCRIPT}
RemainAfterExit=yes
# 디스플레이 매니저가 완전히 시작된 후 실행
ExecStartPre=/bin/sleep 5

[Install]
WantedBy=graphical.target"

# ── 스크립트 설치 (멱등) ────────────────────────────────────────────────────
if write_file_if_changed "$COMPOSITOR_SCRIPT" "$COMPOSITOR_SCRIPT_CONTENT" false; then
  chmod +x "$COMPOSITOR_SCRIPT"
  success "Compositor 부스트 스크립트: ${COMPOSITOR_SCRIPT}"
else
  info "Compositor 부스트 스크립트 이미 동일 — 건너뜀"
fi

# ── 서비스 설치 (멱등) ──────────────────────────────────────────────────────
if write_file_if_changed "$COMPOSITOR_SERVICE" "$COMPOSITOR_SERVICE_CONTENT"; then
  systemctl daemon-reload
  systemctl enable rt-compositor-boost.service 2>/dev/null || true
  success "Compositor 부스트 서비스: ${COMPOSITOR_SERVICE}"
else
  info "서비스가 이미 동일한 설정으로 존재합니다 — 건너뜀"
fi

# ── GUI 환경이면 즉시 실행 ──────────────────────────────────────────────────
# headless 환경에서는 부스트 대상 프로세스가 없으므로 건너뜀
if [[ "$DISPLAY_SERVER" != "headless" ]]; then
  bash "$COMPOSITOR_SCRIPT" 2>/dev/null || true
  success "Compositor 우선순위 즉시 적용 완료"
else
  info "headless 환경 — compositor 부스트는 다음 GUI 부팅 시 자동 적용됩니다"
fi

echo ""

# ── 완료 요약 ───────────────────────────────────────────────────────────────
echo -e "${BOLD}${GREEN}━━━ 설정 완료 ━━━${NC}"
echo ""
echo "검증 명령:"
echo "  cat ${XORG_CONF}                          # X11 anti-tearing 설정"
echo "  systemctl status rt-compositor-boost       # compositor 부스트 서비스"
echo ""
