#!/bin/bash
# setup_udp_optimization.sh — Real-time UDP / ROS 2 NIC Optimization
#
# 실시간 UDP/ROS2(DDS) 통신을 위한 NIC 및 커널 네트워크 스택 최적화.
# IRQ affinity와 함께 사용하면 ControlLoop() jitter를 최소화할 수 있습니다.
#
# 멱등성: 이미 적용된 설정은 건너뛰고, 변경이 필요한 경우에만 적용합니다.
#
# Usage:
#   sudo ./setup_udp_optimization.sh           # NIC 자동 감지
#   sudo ./setup_udp_optimization.sh enp1s0    # NIC 이름 명시
#
# 실행 시점: 부팅 후, ROS2 실행 전 (setup_irq_affinity.sh 이후 권장)
#
# 검증:
#   ethtool -c <NIC>   # coalescing 설정 확인
#   ethtool -k <NIC>   # offload 설정 확인
#   sysctl net.core.rmem_max   # 커널 버퍼 크기 확인

set -euo pipefail

# ── 공통 라이브러리 로드 ────────────────────────────────────────────────────
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=lib/rt_common.sh
source "${SCRIPT_DIR}/lib/rt_common.sh"
make_logger "UDP-OPT"

# error()를 exit 포함 버전으로 재정의
error() { echo -e "${RED}[UDP-OPT]${NC} $*" >&2; exit 1; }

# ── Root check ────────────────────────────────────────────────────────────────
require_root "${1:-}"

# ── Detect or use specified NIC ───────────────────────────────────────────────
NIC="${1:-}"
if [[ -z "$NIC" ]]; then
  NIC=$(detect_physical_nic)
  [[ -z "$NIC" ]] && error "No physical network interface found. Specify one: sudo $0 <NIC>"
  warn "Auto-detected physical NIC: ${NIC}  (specify explicitly if wrong: sudo $0 <NIC>)"
fi

if ! ip link show "$NIC" &>/dev/null; then
  error "Interface '${NIC}' not found. Check with: ip link show"
fi

echo ""
info "Optimizing ${NIC} for Real-time UDP / ROS 2 (DDS)..."
echo ""

# ── ethtool 존재 확인 ─────────────────────────────────────────────────────────
if ! command -v ethtool &>/dev/null; then
  error "ethtool not found. Install with: sudo apt-get install -y ethtool"
fi

# ── Helper: best-effort ethtool (일부 NIC는 특정 설정을 지원하지 않을 수 있음) ──
run_ethtool() {
  if ethtool "$@" 2>/dev/null; then
    return 0
  else
    warn "  ethtool $* — not supported by this NIC (skipping)"
    return 0
  fi
}

# ── 1. NIC Interrupt Coalescing 비활성화 ──────────────────────────────────────
# 데이터가 찰 때까지 기다리지 않고 즉시 인터럽트를 발생시켜 지연 시간을 최소화합니다.
section "Step 1: NIC Interrupt Coalescing..."
COAL_CHANGED=0
COAL_OUT=$(ethtool -c "$NIC" 2>/dev/null) || true
CURRENT_RX_USECS=$(echo "$COAL_OUT" | grep "^rx-usecs:" | awk '{print $2}')
CURRENT_ADAPTIVE_RX=$(echo "$COAL_OUT" | grep "^Adaptive RX:" | awk '{print $2}')

if [[ "$CURRENT_RX_USECS" != "0" ]]; then
  run_ethtool -C "$NIC" rx-usecs 0 tx-usecs 0
  COAL_CHANGED=1
fi
if [[ "$CURRENT_ADAPTIVE_RX" != "off" ]]; then
  run_ethtool -C "$NIC" adaptive-rx off adaptive-tx off
  COAL_CHANGED=1
fi

if [[ "$COAL_CHANGED" -eq 1 ]]; then
  info "  Interrupt coalescing: rx-usecs=0, tx-usecs=0, adaptive=off"
else
  info "  Interrupt coalescing already optimal — skipped"
fi

# ── 2. 오프로딩 기능 비활성화 ────────────────────────────────────────────────
# 하드웨어가 패킷을 병합(Aggregation)하는 기능을 끄면 CPU 부하가 약간 늘지만
# 지연 시간은 줄어듭니다 (DDS RTPS 소형 패킷에 유리).
section "Step 2: NIC Offload Features..."
OFFLOAD_CHANGED=0
OFFLOAD_OUT=$(ethtool -k "$NIC" 2>/dev/null) || true
for feature in generic-receive-offload large-receive-offload tcp-segmentation-offload generic-segmentation-offload; do
  CURRENT=$(echo "$OFFLOAD_OUT" | grep "^${feature}:" | awk '{print $2}')
  if [[ "$CURRENT" != "off" && -n "$CURRENT" ]]; then
    OFFLOAD_CHANGED=1
    break
  fi
done

if [[ "$OFFLOAD_CHANGED" -eq 1 ]]; then
  run_ethtool -K "$NIC" gro off lro off tso off gso off
  info "  Offloads disabled: GRO, LRO, TSO, GSO"
else
  info "  Offloads already disabled — skipped"
fi

# ── 3. 링 버퍼 크기 조정 ──────────────────────────────────────────────────────
# 너무 크면 지연 시간(버퍼링)이 늘고, 너무 작으면 패킷 유실이 발생합니다.
# 1024는 RT/DDS 통신에서 균형 잡힌 값입니다.
section "Step 3: Ring Buffer Size..."
RING_CHANGED=0
RING_OUT=$(ethtool -g "$NIC" 2>/dev/null) || true
# "Current hardware settings:" 이후의 RX/TX 값을 확인
CURRENT_RX_RING=$(echo "$RING_OUT" | awk '/Current hardware settings:/,0' | grep "^RX:" | head -1 | awk '{print $2}')
if [[ -n "$CURRENT_RX_RING" && "$CURRENT_RX_RING" != "1024" ]]; then
  run_ethtool -G "$NIC" rx 1024 tx 1024
  RING_CHANGED=1
fi

if [[ "$RING_CHANGED" -eq 1 ]]; then
  info "  Ring buffer: rx=1024, tx=1024"
else
  info "  Ring buffer already 1024 — skipped"
fi

# ── 4. 커널 네트워크 스택 최적화 (sysctl) ────────────────────────────────────
# ROS 2 (DDS) 통신 시 대용량 데이터 전송 및 빠른 처리를 위한 설정.
# rmem_max/wmem_max: DDS가 setsockopt으로 필요한 만큼 확보할 수 있도록 상한 확대.
# rmem_default/wmem_default: Linux 기본값(212992) 유지 — 모든 소켓에 거대 버퍼 할당 방지.
# 영구 적용: /etc/sysctl.d/99-ros2-udp.conf
section "Step 4: Kernel Network Stack (sysctl)..."

SYSCTL_CONF="/etc/sysctl.d/99-ros2-udp.conf"
SYSCTL_CONTENT="# ROS 2 / DDS Real-time UDP optimization
# Generated by setup_udp_optimization.sh
# Reference: https://docs.ros.org/en/jazzy/How-To-Guides/DDS-tuning.html

# UDP socket receive/send buffer max: 2 GB (DDS가 setsockopt으로 필요한 만큼 확보)
# default는 Linux 기본값(212992) 유지 — 모든 소켓에 거대 버퍼 할당 방지
net.core.rmem_max     = 2147483647
net.core.rmem_default = 212992
net.core.wmem_max     = 2147483647
net.core.wmem_default = 212992

# Input packet queue depth — prevents drops under burst load
net.core.netdev_max_backlog = 5000"

if write_file_if_changed "$SYSCTL_CONF" "$SYSCTL_CONTENT"; then
  info "  Config written to ${SYSCTL_CONF}"
else
  info "  ${SYSCTL_CONF} already up-to-date — skipped"
fi

# 즉시 적용 (재부팅 없이) — conf 파일의 값과 일치하는 fallback
sysctl -p "$SYSCTL_CONF" > /dev/null 2>&1 || {
  sysctl -w net.core.rmem_max=2147483647     > /dev/null
  sysctl -w net.core.rmem_default=212992     > /dev/null
  sysctl -w net.core.wmem_max=2147483647     > /dev/null
  sysctl -w net.core.wmem_default=212992     > /dev/null
  sysctl -w net.core.netdev_max_backlog=5000 > /dev/null
}

info "  rmem_max / wmem_max = 2147483647 (2 GB)"
info "  rmem_default / wmem_default = 212992 (Linux default)"
info "  netdev_max_backlog  = 5000"

# ── 5. IRQ 친화성 안내 ────────────────────────────────────────────────────────
# NIC IRQ affinity는 setup_irq_affinity.sh에서 별도 처리합니다.
# install.sh에서 두 스크립트를 순서대로 실행하면 최대 효과를 얻을 수 있습니다.
echo ""
info "Note: NIC IRQ affinity is managed by setup_irq_affinity.sh (run separately)."
info "      For best results, run both scripts together via install.sh."

echo ""
info "UDP optimization complete."
info ""
info "To verify settings:"
info "  ethtool -c ${NIC}        # coalescing (rx-usecs should be 0)"
info "  ethtool -k ${NIC}        # offloads   (gro, lro, tso, gso should be off)"
info "  ethtool -g ${NIC}        # ring buffer (rx/tx should be 1024)"
info "  sysctl net.core.rmem_max # should be 2147483647"
info ""
info "Settings persist across reboots via ${SYSCTL_CONF}."
info "NIC ethtool settings (coalescing, offload, ring) reset on reboot."
info "To make persistent, add to /etc/rc.local or a systemd oneshot service:"
info "  sudo $(realpath "$0") ${NIC}"
