// AUTO-GENERATED by repo_scripts/scripts/gen_thread_layout.py -- DO NOT EDIT.
// Source of truth: repo_scripts/config/thread_layout.yaml
// Regenerate:      python3 repo_scripts/scripts/gen_thread_layout.py --write
// Drift gate:      python3 repo_scripts/scripts/gen_thread_layout.py --check
//
// Tier constants + the pure tier dispatch. The hand-written prose, the
// ThreadConfig / MpcThreadConfig / SystemThreadConfigs definitions and the
// layout rationale all stay in thread_config.hpp, which includes this file.
//
// Role notes (tier-invariant):
//   rt_callback  DDS recv co-pin (CFS) via launch taskset
//   arm_driver   external process; CM cpu_affinity param (#343)
//   hand_driver  external process; in-process self-pin (#345)
//   nrt_publish  controller-owned publish jthread; shares the nrt_callback slot
#ifndef RTC_BASE_THREAD_CONFIG_GENERATED_HPP_
#define RTC_BASE_THREAD_CONFIG_GENERATED_HPP_

#include "rtc_base/threading/thread_config.hpp"

#include <sched.h>  // SCHED_FIFO, SCHED_OTHER, SCHED_RR

namespace rtc {

// kMpcMaxWorkers sizes MpcThreadConfig::workers and is hand-written in
// thread_config.hpp (it has to precede the struct that uses it, so it cannot
// come from this file). The manifest declares the same number; without this
// assert, lowering max_workers below it silently over-allocates the array.
static_assert(kMpcMaxWorkers == 2, "kMpcMaxWorkers must match max_workers in thread_layout.yaml");

// Slot reserved for OS / DDS / NIC IRQ. ValidateSystemThreadConfigs uses it
// to reject an RT role parked there (issue #349 D-co); emitted from the
// manifest so the rule cannot drift from the layout it guards.
inline constexpr int kOsSlot = 0;

// ── 4-core fallback (layout v4.1) ──
//   Slot 0: OS / DDS / IRQ + arm_driver (CFS 0) + hand_driver (CFS 0) + nrt_callback (CFS 0)
//            + nrt_publish (CFS 0) + nrt_logging (CFS -5)
//   Slot 1: rt_control (FIFO 90)
//   Slot 2: rt_callback (FIFO 70)
//   Slot 3: mpc_main (CFS -5)
//   unpinned (cpu_core = -1): sim_thread, viewer
// degraded — no deterministic RT guarantee.
// Only 4 slots exist, so nrt_* and both driver processes collapse onto
// the OS slot and mpc_main is demoted to CFS.

inline const ThreadConfig kRtControlConfig4Core{.cpu_core = 1,
                                                .sched_policy = SCHED_FIFO,
                                                .sched_priority = 90,
                                                .nice_value = 0,
                                                .name = "rt_control"};

inline const ThreadConfig kRtCallbackConfig4Core{.cpu_core = 2,
                                                 .sched_policy = SCHED_FIFO,
                                                 .sched_priority = 70,
                                                 .nice_value = 0,
                                                 .name = "rt_callback"};

inline const MpcThreadConfig kMpcConfig4Core{
    .main =
        ThreadConfig{
            .cpu_core = 3,
            .sched_policy = SCHED_OTHER,
            .sched_priority = 0,
            .nice_value = -5,
            .name = "mpc_main",
        },
    .num_workers = 0,
    .workers = {},
};

inline const ThreadConfig kArmDriverConfig4Core{.cpu_core = 0,
                                                .sched_policy = SCHED_OTHER,
                                                .sched_priority = 0,
                                                .nice_value = 0,
                                                .name = "arm_driver"};

inline const ThreadConfig kHandDriverConfig4Core{.cpu_core = 0,
                                                 .sched_policy = SCHED_OTHER,
                                                 .sched_priority = 0,
                                                 .nice_value = 0,
                                                 .name = "hand_driver"};

inline const ThreadConfig kNrtCallbackConfig4Core{.cpu_core = 0,
                                                  .sched_policy = SCHED_OTHER,
                                                  .sched_priority = 0,
                                                  .nice_value = 0,
                                                  .name = "nrt_callback"};

inline const ThreadConfig kNrtPublishConfig4Core{.cpu_core = 0,
                                                 .sched_policy = SCHED_OTHER,
                                                 .sched_priority = 0,
                                                 .nice_value = 0,
                                                 .name = "nrt_publish"};

inline const ThreadConfig kNrtLoggingConfig4Core{.cpu_core = 0,
                                                 .sched_policy = SCHED_OTHER,
                                                 .sched_priority = 0,
                                                 .nice_value = -5,
                                                 .name = "nrt_logging"};

inline const ThreadConfig kSimThreadConfig4Core{.cpu_core = -1,
                                                .sched_policy = SCHED_OTHER,
                                                .sched_priority = 0,
                                                .nice_value = 0,
                                                .name = "sim_thread"};

inline const ThreadConfig kViewerConfig4Core{.cpu_core = -1,
                                             .sched_policy = SCHED_OTHER,
                                             .sched_priority = 0,
                                             .nice_value = 0,
                                             .name = "viewer"};

// ── 6-core (layout v4.1) ──
//   Slot 0: OS / DDS / IRQ
//   Slot 1: rt_control (FIFO 90)
//   Slot 2: rt_callback (FIFO 70)
//   Slot 3: mpc_main (FIFO 60)
//   Slot 4: arm_driver (CFS 0) + hand_driver (CFS 0)
//   Slot 5: nrt_callback (CFS 0) + nrt_publish (CFS 0) + nrt_logging (CFS -5)
//   unpinned (cpu_core = -1): sim_thread, viewer
// degraded mode — no deterministic RT guarantee.
// Trade-off: no mpc_worker, arm/hand share one slot, nrt_* share one slot.

inline const ThreadConfig kRtControlConfig{.cpu_core = 1,
                                           .sched_policy = SCHED_FIFO,
                                           .sched_priority = 90,
                                           .nice_value = 0,
                                           .name = "rt_control"};

inline const ThreadConfig kRtCallbackConfig{.cpu_core = 2,
                                            .sched_policy = SCHED_FIFO,
                                            .sched_priority = 70,
                                            .nice_value = 0,
                                            .name = "rt_callback"};

inline const MpcThreadConfig kMpcConfig6Core{
    .main =
        ThreadConfig{
            .cpu_core = 3,
            .sched_policy = SCHED_FIFO,
            .sched_priority = 60,
            .nice_value = 0,
            .name = "mpc_main",
        },
    .num_workers = 0,
    .workers = {},
};

inline const ThreadConfig kArmDriverConfig{.cpu_core = 4,
                                           .sched_policy = SCHED_OTHER,
                                           .sched_priority = 0,
                                           .nice_value = 0,
                                           .name = "arm_driver"};

inline const ThreadConfig kHandDriverConfig{.cpu_core = 4,
                                            .sched_policy = SCHED_OTHER,
                                            .sched_priority = 0,
                                            .nice_value = 0,
                                            .name = "hand_driver"};

inline const ThreadConfig kNrtCallbackConfig{.cpu_core = 5,
                                             .sched_policy = SCHED_OTHER,
                                             .sched_priority = 0,
                                             .nice_value = 0,
                                             .name = "nrt_callback"};

inline const ThreadConfig kNrtPublishConfig{.cpu_core = 5,
                                            .sched_policy = SCHED_OTHER,
                                            .sched_priority = 0,
                                            .nice_value = 0,
                                            .name = "nrt_publish"};

inline const ThreadConfig kNrtLoggingConfig{.cpu_core = 5,
                                            .sched_policy = SCHED_OTHER,
                                            .sched_priority = 0,
                                            .nice_value = -5,
                                            .name = "nrt_logging"};

inline const ThreadConfig kSimThreadConfig{.cpu_core = -1,
                                           .sched_policy = SCHED_OTHER,
                                           .sched_priority = 0,
                                           .nice_value = 0,
                                           .name = "sim_thread"};

inline const ThreadConfig kViewerConfig{.cpu_core = -1,
                                        .sched_policy = SCHED_OTHER,
                                        .sched_priority = 0,
                                        .nice_value = 0,
                                        .name = "viewer"};

// ── 8-core (layout v4.1) ──
//   Slot 0: OS / DDS / IRQ
//   Slot 1: rt_control (FIFO 90)
//   Slot 2: rt_callback (FIFO 70)
//   Slot 3: mpc_main (FIFO 60)
//   Slot 4: arm_driver (CFS 0)
//   Slot 5: hand_driver (CFS 0)
//   Slot 6: nrt_logging (CFS -5)
//   Slot 7: nrt_callback (CFS 0) + nrt_publish (CFS 0)
//   unpinned (cpu_core = -1): sim_thread, viewer
// First tier where arm_driver and hand_driver get dedicated slots.

inline const ThreadConfig kRtControlConfig8Core{.cpu_core = 1,
                                                .sched_policy = SCHED_FIFO,
                                                .sched_priority = 90,
                                                .nice_value = 0,
                                                .name = "rt_control"};

inline const ThreadConfig kRtCallbackConfig8Core{.cpu_core = 2,
                                                 .sched_policy = SCHED_FIFO,
                                                 .sched_priority = 70,
                                                 .nice_value = 0,
                                                 .name = "rt_callback"};

inline const MpcThreadConfig kMpcConfig8Core{
    .main =
        ThreadConfig{
            .cpu_core = 3,
            .sched_policy = SCHED_FIFO,
            .sched_priority = 60,
            .nice_value = 0,
            .name = "mpc_main",
        },
    .num_workers = 0,
    .workers = {},
};

inline const ThreadConfig kArmDriverConfig8Core{.cpu_core = 4,
                                                .sched_policy = SCHED_OTHER,
                                                .sched_priority = 0,
                                                .nice_value = 0,
                                                .name = "arm_driver"};

inline const ThreadConfig kHandDriverConfig8Core{.cpu_core = 5,
                                                 .sched_policy = SCHED_OTHER,
                                                 .sched_priority = 0,
                                                 .nice_value = 0,
                                                 .name = "hand_driver"};

inline const ThreadConfig kNrtCallbackConfig8Core{.cpu_core = 7,
                                                  .sched_policy = SCHED_OTHER,
                                                  .sched_priority = 0,
                                                  .nice_value = 0,
                                                  .name = "nrt_callback"};

inline const ThreadConfig kNrtPublishConfig8Core{.cpu_core = 7,
                                                 .sched_policy = SCHED_OTHER,
                                                 .sched_priority = 0,
                                                 .nice_value = 0,
                                                 .name = "nrt_publish"};

inline const ThreadConfig kNrtLoggingConfig8Core{.cpu_core = 6,
                                                 .sched_policy = SCHED_OTHER,
                                                 .sched_priority = 0,
                                                 .nice_value = -5,
                                                 .name = "nrt_logging"};

inline const ThreadConfig kSimThreadConfig8Core{.cpu_core = -1,
                                                .sched_policy = SCHED_OTHER,
                                                .sched_priority = 0,
                                                .nice_value = 0,
                                                .name = "sim_thread"};

inline const ThreadConfig kViewerConfig8Core{.cpu_core = -1,
                                             .sched_policy = SCHED_OTHER,
                                             .sched_priority = 0,
                                             .nice_value = 0,
                                             .name = "viewer"};

// ── 10-core (layout v4.1) ──
//   Slot 0: OS / DDS / IRQ
//   Slot 1: rt_control (FIFO 90)
//   Slot 2: rt_callback (FIFO 70)
//   Slot 3: mpc_main (FIFO 60)
//   Slot 4: mpc_worker_0 (FIFO 55)
//   Slot 5: arm_driver (CFS 0)
//   Slot 6: hand_driver (CFS 0)
//   Slot 7: nrt_logging (CFS -5)
//   Slot 8: nrt_callback (CFS 0) + nrt_publish (CFS 0)
//   Slot 9: spare
//   unpinned (cpu_core = -1): sim_thread, viewer
// First tier with a parallel MPC worker.

inline const ThreadConfig kRtControlConfig10Core{.cpu_core = 1,
                                                 .sched_policy = SCHED_FIFO,
                                                 .sched_priority = 90,
                                                 .nice_value = 0,
                                                 .name = "rt_control"};

inline const ThreadConfig kRtCallbackConfig10Core{.cpu_core = 2,
                                                  .sched_policy = SCHED_FIFO,
                                                  .sched_priority = 70,
                                                  .nice_value = 0,
                                                  .name = "rt_callback"};

inline const MpcThreadConfig kMpcConfig10Core{
    .main =
        ThreadConfig{
            .cpu_core = 3,
            .sched_policy = SCHED_FIFO,
            .sched_priority = 60,
            .nice_value = 0,
            .name = "mpc_main",
        },
    .num_workers = 1,
    .workers =
        {
            ThreadConfig{
                .cpu_core = 4,
                .sched_policy = SCHED_FIFO,
                .sched_priority = 55,
                .nice_value = 0,
                .name = "mpc_worker_0",
            },
            ThreadConfig{},
        },
};

inline const ThreadConfig kArmDriverConfig10Core{.cpu_core = 5,
                                                 .sched_policy = SCHED_OTHER,
                                                 .sched_priority = 0,
                                                 .nice_value = 0,
                                                 .name = "arm_driver"};

inline const ThreadConfig kHandDriverConfig10Core{.cpu_core = 6,
                                                  .sched_policy = SCHED_OTHER,
                                                  .sched_priority = 0,
                                                  .nice_value = 0,
                                                  .name = "hand_driver"};

inline const ThreadConfig kNrtCallbackConfig10Core{.cpu_core = 8,
                                                   .sched_policy = SCHED_OTHER,
                                                   .sched_priority = 0,
                                                   .nice_value = 0,
                                                   .name = "nrt_callback"};

inline const ThreadConfig kNrtPublishConfig10Core{.cpu_core = 8,
                                                  .sched_policy = SCHED_OTHER,
                                                  .sched_priority = 0,
                                                  .nice_value = 0,
                                                  .name = "nrt_publish"};

inline const ThreadConfig kNrtLoggingConfig10Core{.cpu_core = 7,
                                                  .sched_policy = SCHED_OTHER,
                                                  .sched_priority = 0,
                                                  .nice_value = -5,
                                                  .name = "nrt_logging"};

inline const ThreadConfig kSimThreadConfig10Core{.cpu_core = -1,
                                                 .sched_policy = SCHED_OTHER,
                                                 .sched_priority = 0,
                                                 .nice_value = 0,
                                                 .name = "sim_thread"};

inline const ThreadConfig kViewerConfig10Core{.cpu_core = -1,
                                              .sched_policy = SCHED_OTHER,
                                              .sched_priority = 0,
                                              .nice_value = 0,
                                              .name = "viewer"};

// ── 12-core (primary target) (layout v4.1) ──
//   Slot 0: OS / DDS / IRQ
//   Slot 1: rt_control (FIFO 90)
//   Slot 2: rt_callback (FIFO 70)
//   Slot 3: mpc_main (FIFO 60)
//   Slot 4: mpc_worker_0 (FIFO 55)
//   Slot 5: mpc_worker_1 (FIFO 55)
//   Slot 6: arm_driver (CFS 0)
//   Slot 7: hand_driver (CFS 0)
//   Slot 8: nrt_logging (CFS -5)
//   Slot 9: nrt_callback (CFS 0) + nrt_publish (CFS 0)
//   Slot 10: spare
//   Slot 11: spare
//   unpinned (cpu_core = -1): sim_thread, viewer
// Primary deployment tier. Both MPC workers active.

inline const ThreadConfig kRtControlConfig12Core{.cpu_core = 1,
                                                 .sched_policy = SCHED_FIFO,
                                                 .sched_priority = 90,
                                                 .nice_value = 0,
                                                 .name = "rt_control"};

inline const ThreadConfig kRtCallbackConfig12Core{.cpu_core = 2,
                                                  .sched_policy = SCHED_FIFO,
                                                  .sched_priority = 70,
                                                  .nice_value = 0,
                                                  .name = "rt_callback"};

inline const MpcThreadConfig kMpcConfig12Core{
    .main =
        ThreadConfig{
            .cpu_core = 3,
            .sched_policy = SCHED_FIFO,
            .sched_priority = 60,
            .nice_value = 0,
            .name = "mpc_main",
        },
    .num_workers = 2,
    .workers =
        {
            ThreadConfig{
                .cpu_core = 4,
                .sched_policy = SCHED_FIFO,
                .sched_priority = 55,
                .nice_value = 0,
                .name = "mpc_worker_0",
            },
            ThreadConfig{
                .cpu_core = 5,
                .sched_policy = SCHED_FIFO,
                .sched_priority = 55,
                .nice_value = 0,
                .name = "mpc_worker_1",
            },
        },
};

inline const ThreadConfig kArmDriverConfig12Core{.cpu_core = 6,
                                                 .sched_policy = SCHED_OTHER,
                                                 .sched_priority = 0,
                                                 .nice_value = 0,
                                                 .name = "arm_driver"};

inline const ThreadConfig kHandDriverConfig12Core{.cpu_core = 7,
                                                  .sched_policy = SCHED_OTHER,
                                                  .sched_priority = 0,
                                                  .nice_value = 0,
                                                  .name = "hand_driver"};

inline const ThreadConfig kNrtCallbackConfig12Core{.cpu_core = 9,
                                                   .sched_policy = SCHED_OTHER,
                                                   .sched_priority = 0,
                                                   .nice_value = 0,
                                                   .name = "nrt_callback"};

inline const ThreadConfig kNrtPublishConfig12Core{.cpu_core = 9,
                                                  .sched_policy = SCHED_OTHER,
                                                  .sched_priority = 0,
                                                  .nice_value = 0,
                                                  .name = "nrt_publish"};

inline const ThreadConfig kNrtLoggingConfig12Core{.cpu_core = 8,
                                                  .sched_policy = SCHED_OTHER,
                                                  .sched_priority = 0,
                                                  .nice_value = -5,
                                                  .name = "nrt_logging"};

inline const ThreadConfig kSimThreadConfig12Core{.cpu_core = -1,
                                                 .sched_policy = SCHED_OTHER,
                                                 .sched_priority = 0,
                                                 .nice_value = 0,
                                                 .name = "sim_thread"};

inline const ThreadConfig kViewerConfig12Core{.cpu_core = -1,
                                              .sched_policy = SCHED_OTHER,
                                              .sched_priority = 0,
                                              .nice_value = 0,
                                              .name = "viewer"};

// ── 14-core (layout v4.1) ──
//   Slot 0: OS / DDS / IRQ
//   Slot 1: rt_control (FIFO 90)
//   Slot 2: rt_callback (FIFO 70)
//   Slot 3: mpc_main (FIFO 60)
//   Slot 4: mpc_worker_0 (FIFO 55)
//   Slot 5: mpc_worker_1 (FIFO 55)
//   Slot 6: arm_driver (CFS 0)
//   Slot 7: hand_driver (CFS 0)
//   Slot 8: nrt_logging (CFS -5)
//   Slot 9: nrt_callback (CFS 0) + nrt_publish (CFS 0)
//   Slot 10: spare
//   Slot 11: spare
//   Slot 12: spare
//   Slot 13: spare
//   unpinned (cpu_core = -1): sim_thread, viewer
// Same assignment as the 12-core tier; slots 10+ stay free.

inline const ThreadConfig kRtControlConfig14Core{.cpu_core = 1,
                                                 .sched_policy = SCHED_FIFO,
                                                 .sched_priority = 90,
                                                 .nice_value = 0,
                                                 .name = "rt_control"};

inline const ThreadConfig kRtCallbackConfig14Core{.cpu_core = 2,
                                                  .sched_policy = SCHED_FIFO,
                                                  .sched_priority = 70,
                                                  .nice_value = 0,
                                                  .name = "rt_callback"};

inline const MpcThreadConfig kMpcConfig14Core{
    .main =
        ThreadConfig{
            .cpu_core = 3,
            .sched_policy = SCHED_FIFO,
            .sched_priority = 60,
            .nice_value = 0,
            .name = "mpc_main",
        },
    .num_workers = 2,
    .workers =
        {
            ThreadConfig{
                .cpu_core = 4,
                .sched_policy = SCHED_FIFO,
                .sched_priority = 55,
                .nice_value = 0,
                .name = "mpc_worker_0",
            },
            ThreadConfig{
                .cpu_core = 5,
                .sched_policy = SCHED_FIFO,
                .sched_priority = 55,
                .nice_value = 0,
                .name = "mpc_worker_1",
            },
        },
};

inline const ThreadConfig kArmDriverConfig14Core{.cpu_core = 6,
                                                 .sched_policy = SCHED_OTHER,
                                                 .sched_priority = 0,
                                                 .nice_value = 0,
                                                 .name = "arm_driver"};

inline const ThreadConfig kHandDriverConfig14Core{.cpu_core = 7,
                                                  .sched_policy = SCHED_OTHER,
                                                  .sched_priority = 0,
                                                  .nice_value = 0,
                                                  .name = "hand_driver"};

inline const ThreadConfig kNrtCallbackConfig14Core{.cpu_core = 9,
                                                   .sched_policy = SCHED_OTHER,
                                                   .sched_priority = 0,
                                                   .nice_value = 0,
                                                   .name = "nrt_callback"};

inline const ThreadConfig kNrtPublishConfig14Core{.cpu_core = 9,
                                                  .sched_policy = SCHED_OTHER,
                                                  .sched_priority = 0,
                                                  .nice_value = 0,
                                                  .name = "nrt_publish"};

inline const ThreadConfig kNrtLoggingConfig14Core{.cpu_core = 8,
                                                  .sched_policy = SCHED_OTHER,
                                                  .sched_priority = 0,
                                                  .nice_value = -5,
                                                  .name = "nrt_logging"};

inline const ThreadConfig kSimThreadConfig14Core{.cpu_core = -1,
                                                 .sched_policy = SCHED_OTHER,
                                                 .sched_priority = 0,
                                                 .nice_value = 0,
                                                 .name = "sim_thread"};

inline const ThreadConfig kViewerConfig14Core{.cpu_core = -1,
                                              .sched_policy = SCHED_OTHER,
                                              .sched_priority = 0,
                                              .nice_value = 0,
                                              .name = "viewer"};

// ── 16-core (layout v4.1) ──
//   Slot 0: OS / DDS / IRQ
//   Slot 1: rt_control (FIFO 90)
//   Slot 2: rt_callback (FIFO 70)
//   Slot 3: mpc_main (FIFO 60)
//   Slot 4: mpc_worker_0 (FIFO 55)
//   Slot 5: mpc_worker_1 (FIFO 55)
//   Slot 6: arm_driver (CFS 0)
//   Slot 7: hand_driver (CFS 0)
//   Slot 8: nrt_logging (CFS -5)
//   Slot 9: nrt_callback (CFS 0) + nrt_publish (CFS 0)
//   Slot 10: spare
//   Slot 11: spare
//   Slot 12: spare
//   Slot 13: spare
//   Slot 14: spare
//   Slot 15: spare
//   unpinned (cpu_core = -1): sim_thread, viewer
// Highest tier — 16+ core machines all use this assignment.
// v4.1 removed the prior cset shield "user" on slots 4-8 for RT cluster
// cache locality; slots 10+ remain free for user-level workloads.

inline const ThreadConfig kRtControlConfig16Core{.cpu_core = 1,
                                                 .sched_policy = SCHED_FIFO,
                                                 .sched_priority = 90,
                                                 .nice_value = 0,
                                                 .name = "rt_control"};

inline const ThreadConfig kRtCallbackConfig16Core{.cpu_core = 2,
                                                  .sched_policy = SCHED_FIFO,
                                                  .sched_priority = 70,
                                                  .nice_value = 0,
                                                  .name = "rt_callback"};

inline const MpcThreadConfig kMpcConfig16Core{
    .main =
        ThreadConfig{
            .cpu_core = 3,
            .sched_policy = SCHED_FIFO,
            .sched_priority = 60,
            .nice_value = 0,
            .name = "mpc_main",
        },
    .num_workers = 2,
    .workers =
        {
            ThreadConfig{
                .cpu_core = 4,
                .sched_policy = SCHED_FIFO,
                .sched_priority = 55,
                .nice_value = 0,
                .name = "mpc_worker_0",
            },
            ThreadConfig{
                .cpu_core = 5,
                .sched_policy = SCHED_FIFO,
                .sched_priority = 55,
                .nice_value = 0,
                .name = "mpc_worker_1",
            },
        },
};

inline const ThreadConfig kArmDriverConfig16Core{.cpu_core = 6,
                                                 .sched_policy = SCHED_OTHER,
                                                 .sched_priority = 0,
                                                 .nice_value = 0,
                                                 .name = "arm_driver"};

inline const ThreadConfig kHandDriverConfig16Core{.cpu_core = 7,
                                                  .sched_policy = SCHED_OTHER,
                                                  .sched_priority = 0,
                                                  .nice_value = 0,
                                                  .name = "hand_driver"};

inline const ThreadConfig kNrtCallbackConfig16Core{.cpu_core = 9,
                                                   .sched_policy = SCHED_OTHER,
                                                   .sched_priority = 0,
                                                   .nice_value = 0,
                                                   .name = "nrt_callback"};

inline const ThreadConfig kNrtPublishConfig16Core{.cpu_core = 9,
                                                  .sched_policy = SCHED_OTHER,
                                                  .sched_priority = 0,
                                                  .nice_value = 0,
                                                  .name = "nrt_publish"};

inline const ThreadConfig kNrtLoggingConfig16Core{.cpu_core = 8,
                                                  .sched_policy = SCHED_OTHER,
                                                  .sched_priority = 0,
                                                  .nice_value = -5,
                                                  .name = "nrt_logging"};

inline const ThreadConfig kSimThreadConfig16Core{.cpu_core = -1,
                                                 .sched_policy = SCHED_OTHER,
                                                 .sched_priority = 0,
                                                 .nice_value = 0,
                                                 .name = "sim_thread"};

inline const ThreadConfig kViewerConfig16Core{.cpu_core = -1,
                                              .sched_policy = SCHED_OTHER,
                                              .sched_priority = 0,
                                              .nice_value = 0,
                                              .name = "viewer"};

// Pure tier dispatch. SelectThreadConfigs() in thread_utils.hpp is the
// runtime-probing wrapper; this overload takes the core count explicitly so
// tests can sweep tiers the host machine does not have.
inline SystemThreadConfigs SelectThreadConfigsForCoreCount(int ncpu) noexcept {
  if (ncpu >= 16) {
    return {.rt_control = kRtControlConfig16Core,
            .rt_callback = kRtCallbackConfig16Core,
            .nrt_logging = kNrtLoggingConfig16Core,
            .nrt_callback = kNrtCallbackConfig16Core,
            .nrt_publish = kNrtPublishConfig16Core,
            .arm_driver = kArmDriverConfig16Core,
            .hand_driver = kHandDriverConfig16Core,
            .sim_thread = kSimThreadConfig16Core,
            .viewer = kViewerConfig16Core,
            .mpc = kMpcConfig16Core};
  }
  if (ncpu >= 14) {
    return {.rt_control = kRtControlConfig14Core,
            .rt_callback = kRtCallbackConfig14Core,
            .nrt_logging = kNrtLoggingConfig14Core,
            .nrt_callback = kNrtCallbackConfig14Core,
            .nrt_publish = kNrtPublishConfig14Core,
            .arm_driver = kArmDriverConfig14Core,
            .hand_driver = kHandDriverConfig14Core,
            .sim_thread = kSimThreadConfig14Core,
            .viewer = kViewerConfig14Core,
            .mpc = kMpcConfig14Core};
  }
  if (ncpu >= 12) {
    return {.rt_control = kRtControlConfig12Core,
            .rt_callback = kRtCallbackConfig12Core,
            .nrt_logging = kNrtLoggingConfig12Core,
            .nrt_callback = kNrtCallbackConfig12Core,
            .nrt_publish = kNrtPublishConfig12Core,
            .arm_driver = kArmDriverConfig12Core,
            .hand_driver = kHandDriverConfig12Core,
            .sim_thread = kSimThreadConfig12Core,
            .viewer = kViewerConfig12Core,
            .mpc = kMpcConfig12Core};
  }
  if (ncpu >= 10) {
    return {.rt_control = kRtControlConfig10Core,
            .rt_callback = kRtCallbackConfig10Core,
            .nrt_logging = kNrtLoggingConfig10Core,
            .nrt_callback = kNrtCallbackConfig10Core,
            .nrt_publish = kNrtPublishConfig10Core,
            .arm_driver = kArmDriverConfig10Core,
            .hand_driver = kHandDriverConfig10Core,
            .sim_thread = kSimThreadConfig10Core,
            .viewer = kViewerConfig10Core,
            .mpc = kMpcConfig10Core};
  }
  if (ncpu >= 8) {
    return {.rt_control = kRtControlConfig8Core,
            .rt_callback = kRtCallbackConfig8Core,
            .nrt_logging = kNrtLoggingConfig8Core,
            .nrt_callback = kNrtCallbackConfig8Core,
            .nrt_publish = kNrtPublishConfig8Core,
            .arm_driver = kArmDriverConfig8Core,
            .hand_driver = kHandDriverConfig8Core,
            .sim_thread = kSimThreadConfig8Core,
            .viewer = kViewerConfig8Core,
            .mpc = kMpcConfig8Core};
  }
  if (ncpu >= 6) {
    return {.rt_control = kRtControlConfig,
            .rt_callback = kRtCallbackConfig,
            .nrt_logging = kNrtLoggingConfig,
            .nrt_callback = kNrtCallbackConfig,
            .nrt_publish = kNrtPublishConfig,
            .arm_driver = kArmDriverConfig,
            .hand_driver = kHandDriverConfig,
            .sim_thread = kSimThreadConfig,
            .viewer = kViewerConfig,
            .mpc = kMpcConfig6Core};
  }
  return {.rt_control = kRtControlConfig4Core,
          .rt_callback = kRtCallbackConfig4Core,
          .nrt_logging = kNrtLoggingConfig4Core,
          .nrt_callback = kNrtCallbackConfig4Core,
          .nrt_publish = kNrtPublishConfig4Core,
          .arm_driver = kArmDriverConfig4Core,
          .hand_driver = kHandDriverConfig4Core,
          .sim_thread = kSimThreadConfig4Core,
          .viewer = kViewerConfig4Core,
          .mpc = kMpcConfig4Core};
}

}  // namespace rtc

#endif  // RTC_BASE_THREAD_CONFIG_GENERATED_HPP_
