// AUTO-GENERATED by repo_scripts/scripts/gen_thread_layout.py -- DO NOT EDIT.
// Source of truth: repo_scripts/config/thread_layout.yaml
// Regenerate:      python3 repo_scripts/scripts/gen_thread_layout.py --write
// Drift gate:      python3 repo_scripts/scripts/gen_thread_layout.py --check
//
// Tier constants + the pure tier dispatch. The hand-written prose, the
// ThreadConfig / MpcThreadConfig / SystemThreadConfigs definitions and the
// layout rationale all stay in thread_config.hpp, which includes this file.
//
// Role notes (tier-invariant):
//   rt_callback  DDS recv co-pin (CFS) via launch taskset
//   arm_driver   external process; CM cpu_affinity param (#343)
//   hand_driver  external process; in-process self-pin (#345)
#ifndef RTC_BASE_THREAD_CONFIG_GENERATED_HPP_
#define RTC_BASE_THREAD_CONFIG_GENERATED_HPP_

#include "rtc_base/threading/thread_config.hpp"

#include <sched.h>  // SCHED_FIFO, SCHED_OTHER, SCHED_RR

namespace rtc {

// ── 4-core fallback (layout v4.1) ──
//   Slot 0: OS / DDS / IRQ + arm_driver (CFS 0) + hand_driver (CFS 0) + nrt_callback (CFS 0)
//            + nrt_logging (CFS -5)
//   Slot 1: rt_control (FIFO 90)
//   Slot 2: rt_callback (FIFO 70)
//   Slot 3: mpc_main (CFS -5)
//   unpinned (cpu_core = -1): sim_thread, viewer
// degraded — no deterministic RT guarantee.
// Only 4 slots exist, so nrt_* and both driver processes collapse onto
// the OS slot and mpc_main is demoted to CFS.

inline const ThreadConfig kRtControlConfig4Core{.cpu_core = 1,
                                                .sched_policy = SCHED_FIFO,
                                                .sched_priority = 90,
                                                .nice_value = 0,
                                                .name = "rt_control"};

inline const ThreadConfig kRtCallbackConfig4Core{.cpu_core = 2,
                                                 .sched_policy = SCHED_FIFO,
                                                 .sched_priority = 70,
                                                 .nice_value = 0,
                                                 .name = "rt_callback"};

inline const MpcThreadConfig kMpcConfig4Core{
    .main =
        ThreadConfig{
            .cpu_core = 3,
            .sched_policy = SCHED_OTHER,
            .sched_priority = 0,
            .nice_value = -5,
            .name = "mpc_main",
        },
    .num_workers = 0,
    .workers = {},
};

inline const ThreadConfig kArmDriverConfig4Core{.cpu_core = 0,
                                                .sched_policy = SCHED_OTHER,
                                                .sched_priority = 0,
                                                .nice_value = 0,
                                                .name = "arm_driver"};

inline const ThreadConfig kHandDriverConfig4Core{.cpu_core = 0,
                                                 .sched_policy = SCHED_OTHER,
                                                 .sched_priority = 0,
                                                 .nice_value = 0,
                                                 .name = "hand_driver"};

inline const ThreadConfig kNrtCallbackConfig4Core{.cpu_core = 0,
                                                  .sched_policy = SCHED_OTHER,
                                                  .sched_priority = 0,
                                                  .nice_value = 0,
                                                  .name = "nrt_callback"};

inline const ThreadConfig kNrtLoggingConfig4Core{.cpu_core = 0,
                                                 .sched_policy = SCHED_OTHER,
                                                 .sched_priority = 0,
                                                 .nice_value = -5,
                                                 .name = "nrt_logging"};

inline const ThreadConfig kSimThreadConfig4Core{.cpu_core = -1,
                                                .sched_policy = SCHED_OTHER,
                                                .sched_priority = 0,
                                                .nice_value = 0,
                                                .name = "sim_thread"};

inline const ThreadConfig kViewerConfig4Core{.cpu_core = -1,
                                             .sched_policy = SCHED_OTHER,
                                             .sched_priority = 0,
                                             .nice_value = 0,
                                             .name = "viewer"};

// ── 6-core (layout v4.1) ──
//   Slot 0: OS / DDS / IRQ
//   Slot 1: rt_control (FIFO 90)
//   Slot 2: rt_callback (FIFO 70)
//   Slot 3: mpc_main (FIFO 60)
//   Slot 4: arm_driver (CFS 0) + hand_driver (CFS 0)
//   Slot 5: nrt_callback (CFS 0) + nrt_logging (CFS -5)
//   unpinned (cpu_core = -1): sim_thread, viewer
// degraded mode — no deterministic RT guarantee.
// Trade-off: no mpc_worker, arm/hand share one slot, nrt_* share one slot.

inline const ThreadConfig kRtControlConfig{.cpu_core = 1,
                                           .sched_policy = SCHED_FIFO,
                                           .sched_priority = 90,
                                           .nice_value = 0,
                                           .name = "rt_control"};

inline const ThreadConfig kRtCallbackConfig{.cpu_core = 2,
                                            .sched_policy = SCHED_FIFO,
                                            .sched_priority = 70,
                                            .nice_value = 0,
                                            .name = "rt_callback"};

inline const MpcThreadConfig kMpcConfig6Core{
    .main =
        ThreadConfig{
            .cpu_core = 3,
            .sched_policy = SCHED_FIFO,
            .sched_priority = 60,
            .nice_value = 0,
            .name = "mpc_main",
        },
    .num_workers = 0,
    .workers = {},
};

inline const ThreadConfig kArmDriverConfig{.cpu_core = 4,
                                           .sched_policy = SCHED_OTHER,
                                           .sched_priority = 0,
                                           .nice_value = 0,
                                           .name = "arm_driver"};

inline const ThreadConfig kHandDriverConfig{.cpu_core = 4,
                                            .sched_policy = SCHED_OTHER,
                                            .sched_priority = 0,
                                            .nice_value = 0,
                                            .name = "hand_driver"};

inline const ThreadConfig kNrtCallbackConfig{.cpu_core = 5,
                                             .sched_policy = SCHED_OTHER,
                                             .sched_priority = 0,
                                             .nice_value = 0,
                                             .name = "nrt_callback"};

inline const ThreadConfig kNrtLoggingConfig{.cpu_core = 5,
                                            .sched_policy = SCHED_OTHER,
                                            .sched_priority = 0,
                                            .nice_value = -5,
                                            .name = "nrt_logging"};

inline const ThreadConfig kSimThreadConfig{.cpu_core = -1,
                                           .sched_policy = SCHED_OTHER,
                                           .sched_priority = 0,
                                           .nice_value = 0,
                                           .name = "sim_thread"};

inline const ThreadConfig kViewerConfig{.cpu_core = -1,
                                        .sched_policy = SCHED_OTHER,
                                        .sched_priority = 0,
                                        .nice_value = 0,
                                        .name = "viewer"};

// ── 8-core (layout v4.1) ──
//   Slot 0: OS / DDS / IRQ
//   Slot 1: rt_control (FIFO 90)
//   Slot 2: rt_callback (FIFO 70)
//   Slot 3: mpc_main (FIFO 60)
//   Slot 4: arm_driver (CFS 0)
//   Slot 5: hand_driver (CFS 0)
//   Slot 6: nrt_logging (CFS -5)
//   Slot 7: nrt_callback (CFS 0)
//   unpinned (cpu_core = -1): sim_thread, viewer
// First tier where arm_driver and hand_driver get dedicated slots.

inline const ThreadConfig kRtControlConfig8Core{.cpu_core = 1,
                                                .sched_policy = SCHED_FIFO,
                                                .sched_priority = 90,
                                                .nice_value = 0,
                                                .name = "rt_control"};

inline const ThreadConfig kRtCallbackConfig8Core{.cpu_core = 2,
                                                 .sched_policy = SCHED_FIFO,
                                                 .sched_priority = 70,
                                                 .nice_value = 0,
                                                 .name = "rt_callback"};

inline const MpcThreadConfig kMpcConfig8Core{
    .main =
        ThreadConfig{
            .cpu_core = 3,
            .sched_policy = SCHED_FIFO,
            .sched_priority = 60,
            .nice_value = 0,
            .name = "mpc_main",
        },
    .num_workers = 0,
    .workers = {},
};

inline const ThreadConfig kArmDriverConfig8Core{.cpu_core = 4,
                                                .sched_policy = SCHED_OTHER,
                                                .sched_priority = 0,
                                                .nice_value = 0,
                                                .name = "arm_driver"};

inline const ThreadConfig kHandDriverConfig8Core{.cpu_core = 5,
                                                 .sched_policy = SCHED_OTHER,
                                                 .sched_priority = 0,
                                                 .nice_value = 0,
                                                 .name = "hand_driver"};

inline const ThreadConfig kNrtCallbackConfig8Core{.cpu_core = 7,
                                                  .sched_policy = SCHED_OTHER,
                                                  .sched_priority = 0,
                                                  .nice_value = 0,
                                                  .name = "nrt_callback"};

inline const ThreadConfig kNrtLoggingConfig8Core{.cpu_core = 6,
                                                 .sched_policy = SCHED_OTHER,
                                                 .sched_priority = 0,
                                                 .nice_value = -5,
                                                 .name = "nrt_logging"};

inline const ThreadConfig kSimThreadConfig8Core{.cpu_core = -1,
                                                .sched_policy = SCHED_OTHER,
                                                .sched_priority = 0,
                                                .nice_value = 0,
                                                .name = "sim_thread"};

inline const ThreadConfig kViewerConfig8Core{.cpu_core = -1,
                                             .sched_policy = SCHED_OTHER,
                                             .sched_priority = 0,
                                             .nice_value = 0,
                                             .name = "viewer"};

// ── 10-core (layout v4.1) ──
//   Slot 0: OS / DDS / IRQ
//   Slot 1: rt_control (FIFO 90)
//   Slot 2: rt_callback (FIFO 70)
//   Slot 3: mpc_main (FIFO 60)
//   Slot 4: mpc_worker_0 (FIFO 55)
//   Slot 5: arm_driver (CFS 0)
//   Slot 6: hand_driver (CFS 0)
//   Slot 7: nrt_logging (CFS -5)
//   Slot 8: nrt_callback (CFS 0)
//   Slot 9: spare
//   unpinned (cpu_core = -1): sim_thread, viewer
// First tier with a parallel MPC worker.

inline const ThreadConfig kRtControlConfig10Core{.cpu_core = 1,
                                                 .sched_policy = SCHED_FIFO,
                                                 .sched_priority = 90,
                                                 .nice_value = 0,
                                                 .name = "rt_control"};

inline const ThreadConfig kRtCallbackConfig10Core{.cpu_core = 2,
                                                  .sched_policy = SCHED_FIFO,
                                                  .sched_priority = 70,
                                                  .nice_value = 0,
                                                  .name = "rt_callback"};

inline const MpcThreadConfig kMpcConfig10Core{
    .main =
        ThreadConfig{
            .cpu_core = 3,
            .sched_policy = SCHED_FIFO,
            .sched_priority = 60,
            .nice_value = 0,
            .name = "mpc_main",
        },
    .num_workers = 1,
    .workers =
        {
            ThreadConfig{
                .cpu_core = 4,
                .sched_policy = SCHED_FIFO,
                .sched_priority = 55,
                .nice_value = 0,
                .name = "mpc_worker_0",
            },
            ThreadConfig{},
        },
};

inline const ThreadConfig kArmDriverConfig10Core{.cpu_core = 5,
                                                 .sched_policy = SCHED_OTHER,
                                                 .sched_priority = 0,
                                                 .nice_value = 0,
                                                 .name = "arm_driver"};

inline const ThreadConfig kHandDriverConfig10Core{.cpu_core = 6,
                                                  .sched_policy = SCHED_OTHER,
                                                  .sched_priority = 0,
                                                  .nice_value = 0,
                                                  .name = "hand_driver"};

inline const ThreadConfig kNrtCallbackConfig10Core{.cpu_core = 8,
                                                   .sched_policy = SCHED_OTHER,
                                                   .sched_priority = 0,
                                                   .nice_value = 0,
                                                   .name = "nrt_callback"};

inline const ThreadConfig kNrtLoggingConfig10Core{.cpu_core = 7,
                                                  .sched_policy = SCHED_OTHER,
                                                  .sched_priority = 0,
                                                  .nice_value = -5,
                                                  .name = "nrt_logging"};

inline const ThreadConfig kSimThreadConfig10Core{.cpu_core = -1,
                                                 .sched_policy = SCHED_OTHER,
                                                 .sched_priority = 0,
                                                 .nice_value = 0,
                                                 .name = "sim_thread"};

inline const ThreadConfig kViewerConfig10Core{.cpu_core = -1,
                                              .sched_policy = SCHED_OTHER,
                                              .sched_priority = 0,
                                              .nice_value = 0,
                                              .name = "viewer"};

// ── 12-core (primary target) (layout v4.1) ──
//   Slot 0: OS / DDS / IRQ
//   Slot 1: rt_control (FIFO 90)
//   Slot 2: rt_callback (FIFO 70)
//   Slot 3: mpc_main (FIFO 60)
//   Slot 4: mpc_worker_0 (FIFO 55)
//   Slot 5: mpc_worker_1 (FIFO 55)
//   Slot 6: arm_driver (CFS 0)
//   Slot 7: hand_driver (CFS 0)
//   Slot 8: nrt_logging (CFS -5)
//   Slot 9: nrt_callback (CFS 0)
//   Slot 10: spare
//   Slot 11: spare
//   unpinned (cpu_core = -1): sim_thread, viewer
// Primary deployment tier. Both MPC workers active.

inline const ThreadConfig kRtControlConfig12Core{.cpu_core = 1,
                                                 .sched_policy = SCHED_FIFO,
                                                 .sched_priority = 90,
                                                 .nice_value = 0,
                                                 .name = "rt_control"};

inline const ThreadConfig kRtCallbackConfig12Core{.cpu_core = 2,
                                                  .sched_policy = SCHED_FIFO,
                                                  .sched_priority = 70,
                                                  .nice_value = 0,
                                                  .name = "rt_callback"};

inline const MpcThreadConfig kMpcConfig12Core{
    .main =
        ThreadConfig{
            .cpu_core = 3,
            .sched_policy = SCHED_FIFO,
            .sched_priority = 60,
            .nice_value = 0,
            .name = "mpc_main",
        },
    .num_workers = 2,
    .workers =
        {
            ThreadConfig{
                .cpu_core = 4,
                .sched_policy = SCHED_FIFO,
                .sched_priority = 55,
                .nice_value = 0,
                .name = "mpc_worker_0",
            },
            ThreadConfig{
                .cpu_core = 5,
                .sched_policy = SCHED_FIFO,
                .sched_priority = 55,
                .nice_value = 0,
                .name = "mpc_worker_1",
            },
        },
};

inline const ThreadConfig kArmDriverConfig12Core{.cpu_core = 6,
                                                 .sched_policy = SCHED_OTHER,
                                                 .sched_priority = 0,
                                                 .nice_value = 0,
                                                 .name = "arm_driver"};

inline const ThreadConfig kHandDriverConfig12Core{.cpu_core = 7,
                                                  .sched_policy = SCHED_OTHER,
                                                  .sched_priority = 0,
                                                  .nice_value = 0,
                                                  .name = "hand_driver"};

inline const ThreadConfig kNrtCallbackConfig12Core{.cpu_core = 9,
                                                   .sched_policy = SCHED_OTHER,
                                                   .sched_priority = 0,
                                                   .nice_value = 0,
                                                   .name = "nrt_callback"};

inline const ThreadConfig kNrtLoggingConfig12Core{.cpu_core = 8,
                                                  .sched_policy = SCHED_OTHER,
                                                  .sched_priority = 0,
                                                  .nice_value = -5,
                                                  .name = "nrt_logging"};

inline const ThreadConfig kSimThreadConfig12Core{.cpu_core = -1,
                                                 .sched_policy = SCHED_OTHER,
                                                 .sched_priority = 0,
                                                 .nice_value = 0,
                                                 .name = "sim_thread"};

inline const ThreadConfig kViewerConfig12Core{.cpu_core = -1,
                                              .sched_policy = SCHED_OTHER,
                                              .sched_priority = 0,
                                              .nice_value = 0,
                                              .name = "viewer"};

// ── 14-core (layout v4.1) ──
//   Slot 0: OS / DDS / IRQ
//   Slot 1: rt_control (FIFO 90)
//   Slot 2: rt_callback (FIFO 70)
//   Slot 3: mpc_main (FIFO 60)
//   Slot 4: mpc_worker_0 (FIFO 55)
//   Slot 5: mpc_worker_1 (FIFO 55)
//   Slot 6: arm_driver (CFS 0)
//   Slot 7: hand_driver (CFS 0)
//   Slot 8: nrt_logging (CFS -5)
//   Slot 9: nrt_callback (CFS 0)
//   Slot 10: spare
//   Slot 11: spare
//   Slot 12: spare
//   Slot 13: spare
//   unpinned (cpu_core = -1): sim_thread, viewer
// Same assignment as the 12-core tier; slots 10+ stay free.

inline const ThreadConfig kRtControlConfig14Core{.cpu_core = 1,
                                                 .sched_policy = SCHED_FIFO,
                                                 .sched_priority = 90,
                                                 .nice_value = 0,
                                                 .name = "rt_control"};

inline const ThreadConfig kRtCallbackConfig14Core{.cpu_core = 2,
                                                  .sched_policy = SCHED_FIFO,
                                                  .sched_priority = 70,
                                                  .nice_value = 0,
                                                  .name = "rt_callback"};

inline const MpcThreadConfig kMpcConfig14Core{
    .main =
        ThreadConfig{
            .cpu_core = 3,
            .sched_policy = SCHED_FIFO,
            .sched_priority = 60,
            .nice_value = 0,
            .name = "mpc_main",
        },
    .num_workers = 2,
    .workers =
        {
            ThreadConfig{
                .cpu_core = 4,
                .sched_policy = SCHED_FIFO,
                .sched_priority = 55,
                .nice_value = 0,
                .name = "mpc_worker_0",
            },
            ThreadConfig{
                .cpu_core = 5,
                .sched_policy = SCHED_FIFO,
                .sched_priority = 55,
                .nice_value = 0,
                .name = "mpc_worker_1",
            },
        },
};

inline const ThreadConfig kArmDriverConfig14Core{.cpu_core = 6,
                                                 .sched_policy = SCHED_OTHER,
                                                 .sched_priority = 0,
                                                 .nice_value = 0,
                                                 .name = "arm_driver"};

inline const ThreadConfig kHandDriverConfig14Core{.cpu_core = 7,
                                                  .sched_policy = SCHED_OTHER,
                                                  .sched_priority = 0,
                                                  .nice_value = 0,
                                                  .name = "hand_driver"};

inline const ThreadConfig kNrtCallbackConfig14Core{.cpu_core = 9,
                                                   .sched_policy = SCHED_OTHER,
                                                   .sched_priority = 0,
                                                   .nice_value = 0,
                                                   .name = "nrt_callback"};

inline const ThreadConfig kNrtLoggingConfig14Core{.cpu_core = 8,
                                                  .sched_policy = SCHED_OTHER,
                                                  .sched_priority = 0,
                                                  .nice_value = -5,
                                                  .name = "nrt_logging"};

inline const ThreadConfig kSimThreadConfig14Core{.cpu_core = -1,
                                                 .sched_policy = SCHED_OTHER,
                                                 .sched_priority = 0,
                                                 .nice_value = 0,
                                                 .name = "sim_thread"};

inline const ThreadConfig kViewerConfig14Core{.cpu_core = -1,
                                              .sched_policy = SCHED_OTHER,
                                              .sched_priority = 0,
                                              .nice_value = 0,
                                              .name = "viewer"};

// ── 16-core (layout v4.1) ──
//   Slot 0: OS / DDS / IRQ
//   Slot 1: rt_control (FIFO 90)
//   Slot 2: rt_callback (FIFO 70)
//   Slot 3: mpc_main (FIFO 60)
//   Slot 4: mpc_worker_0 (FIFO 55)
//   Slot 5: mpc_worker_1 (FIFO 55)
//   Slot 6: arm_driver (CFS 0)
//   Slot 7: hand_driver (CFS 0)
//   Slot 8: nrt_logging (CFS -5)
//   Slot 9: nrt_callback (CFS 0)
//   Slot 10: spare
//   Slot 11: spare
//   Slot 12: spare
//   Slot 13: spare
//   Slot 14: spare
//   Slot 15: spare
//   unpinned (cpu_core = -1): sim_thread, viewer
// Highest tier — 16+ core machines all use this assignment.
// v4.1 removed the prior cset shield "user" on slots 4-8 for RT cluster
// cache locality; slots 10+ remain free for user-level workloads.

inline const ThreadConfig kRtControlConfig16Core{.cpu_core = 1,
                                                 .sched_policy = SCHED_FIFO,
                                                 .sched_priority = 90,
                                                 .nice_value = 0,
                                                 .name = "rt_control"};

inline const ThreadConfig kRtCallbackConfig16Core{.cpu_core = 2,
                                                  .sched_policy = SCHED_FIFO,
                                                  .sched_priority = 70,
                                                  .nice_value = 0,
                                                  .name = "rt_callback"};

inline const MpcThreadConfig kMpcConfig16Core{
    .main =
        ThreadConfig{
            .cpu_core = 3,
            .sched_policy = SCHED_FIFO,
            .sched_priority = 60,
            .nice_value = 0,
            .name = "mpc_main",
        },
    .num_workers = 2,
    .workers =
        {
            ThreadConfig{
                .cpu_core = 4,
                .sched_policy = SCHED_FIFO,
                .sched_priority = 55,
                .nice_value = 0,
                .name = "mpc_worker_0",
            },
            ThreadConfig{
                .cpu_core = 5,
                .sched_policy = SCHED_FIFO,
                .sched_priority = 55,
                .nice_value = 0,
                .name = "mpc_worker_1",
            },
        },
};

inline const ThreadConfig kArmDriverConfig16Core{.cpu_core = 6,
                                                 .sched_policy = SCHED_OTHER,
                                                 .sched_priority = 0,
                                                 .nice_value = 0,
                                                 .name = "arm_driver"};

inline const ThreadConfig kHandDriverConfig16Core{.cpu_core = 7,
                                                  .sched_policy = SCHED_OTHER,
                                                  .sched_priority = 0,
                                                  .nice_value = 0,
                                                  .name = "hand_driver"};

inline const ThreadConfig kNrtCallbackConfig16Core{.cpu_core = 9,
                                                   .sched_policy = SCHED_OTHER,
                                                   .sched_priority = 0,
                                                   .nice_value = 0,
                                                   .name = "nrt_callback"};

inline const ThreadConfig kNrtLoggingConfig16Core{.cpu_core = 8,
                                                  .sched_policy = SCHED_OTHER,
                                                  .sched_priority = 0,
                                                  .nice_value = -5,
                                                  .name = "nrt_logging"};

inline const ThreadConfig kSimThreadConfig16Core{.cpu_core = -1,
                                                 .sched_policy = SCHED_OTHER,
                                                 .sched_priority = 0,
                                                 .nice_value = 0,
                                                 .name = "sim_thread"};

inline const ThreadConfig kViewerConfig16Core{.cpu_core = -1,
                                              .sched_policy = SCHED_OTHER,
                                              .sched_priority = 0,
                                              .nice_value = 0,
                                              .name = "viewer"};

// Pure tier dispatch. SelectThreadConfigs() in thread_utils.hpp is the
// runtime-probing wrapper; this overload takes the core count explicitly so
// tests can sweep tiers the host machine does not have.
inline SystemThreadConfigs SelectThreadConfigsForCoreCount(int ncpu) noexcept {
  if (ncpu >= 16) {
    return {kRtControlConfig16Core,   kRtCallbackConfig16Core, kNrtLoggingConfig16Core,
            kNrtCallbackConfig16Core, kArmDriverConfig16Core,  kHandDriverConfig16Core,
            kSimThreadConfig16Core,   kViewerConfig16Core,     kMpcConfig16Core};
  }
  if (ncpu >= 14) {
    return {kRtControlConfig14Core,   kRtCallbackConfig14Core, kNrtLoggingConfig14Core,
            kNrtCallbackConfig14Core, kArmDriverConfig14Core,  kHandDriverConfig14Core,
            kSimThreadConfig14Core,   kViewerConfig14Core,     kMpcConfig14Core};
  }
  if (ncpu >= 12) {
    return {kRtControlConfig12Core,   kRtCallbackConfig12Core, kNrtLoggingConfig12Core,
            kNrtCallbackConfig12Core, kArmDriverConfig12Core,  kHandDriverConfig12Core,
            kSimThreadConfig12Core,   kViewerConfig12Core,     kMpcConfig12Core};
  }
  if (ncpu >= 10) {
    return {kRtControlConfig10Core,   kRtCallbackConfig10Core, kNrtLoggingConfig10Core,
            kNrtCallbackConfig10Core, kArmDriverConfig10Core,  kHandDriverConfig10Core,
            kSimThreadConfig10Core,   kViewerConfig10Core,     kMpcConfig10Core};
  }
  if (ncpu >= 8) {
    return {kRtControlConfig8Core,   kRtCallbackConfig8Core, kNrtLoggingConfig8Core,
            kNrtCallbackConfig8Core, kArmDriverConfig8Core,  kHandDriverConfig8Core,
            kSimThreadConfig8Core,   kViewerConfig8Core,     kMpcConfig8Core};
  }
  if (ncpu >= 6) {
    return {kRtControlConfig,   kRtCallbackConfig, kNrtLoggingConfig,
            kNrtCallbackConfig, kArmDriverConfig,  kHandDriverConfig,
            kSimThreadConfig,   kViewerConfig,     kMpcConfig6Core};
  }
  return {kRtControlConfig4Core,   kRtCallbackConfig4Core, kNrtLoggingConfig4Core,
          kNrtCallbackConfig4Core, kArmDriverConfig4Core,  kHandDriverConfig4Core,
          kSimThreadConfig4Core,   kViewerConfig4Core,     kMpcConfig4Core};
}

}  // namespace rtc

#endif  // RTC_BASE_THREAD_CONFIG_GENERATED_HPP_
