"""AUTO-GENERATED by repo_scripts/scripts/gen_thread_layout.py -- DO NOT EDIT.
Source of truth: repo_scripts/config/thread_layout.yaml
Regenerate:      python3 repo_scripts/scripts/gen_thread_layout.py --write
Drift gate:      python3 repo_scripts/scripts/gen_thread_layout.py --check

Full per-tier role table mirrored for launch-time ``taskset`` pinning.
``rtc_tools.launch.thread_layout`` is the hand-written adapter that exposes
the stable public API on top of this table.

Every ``slot`` is a ThreadConfig::cpu_core *slot index*, not a kernel logical
CPU id; ``-1`` means "do not pin".
"""

from __future__ import annotations

from typing import NamedTuple


class RoleSpec(NamedTuple):
    """One role's placement on one tier."""

    slot: int
    policy: str
    priority: int
    nice: int


LAYOUT_VERSION = "v4.1"
OS_SLOT = 0
MAX_WORKERS = 2

# Dispatch order: the first tier whose threshold is met wins; the last entry
# is the fallback used below every threshold.
TIER_THRESHOLDS: tuple[tuple[int, int], ...] = (
    (16, 16),
    (14, 14),
    (12, 12),
    (10, 10),
    (8, 8),
    (6, 6),
)
FALLBACK_TIER = 4

ROLE_SPECS: dict[int, dict[str, RoleSpec]] = {
    4: {
        "rt_control": RoleSpec(1, "FIFO", 90, 0),
        "rt_callback": RoleSpec(2, "FIFO", 70, 0),
        "mpc_main": RoleSpec(3, "OTHER", 0, -5),
        "arm_driver": RoleSpec(0, "OTHER", 0, 0),
        "hand_driver": RoleSpec(0, "OTHER", 0, 0),
        "nrt_callback": RoleSpec(0, "OTHER", 0, 0),
        "nrt_publish": RoleSpec(0, "OTHER", 0, 0),
        "nrt_logging": RoleSpec(0, "OTHER", 0, -5),
        "sim_thread": RoleSpec(-1, "OTHER", 0, 0),
        "viewer": RoleSpec(-1, "OTHER", 0, 0),
    },
    6: {
        "rt_control": RoleSpec(1, "FIFO", 90, 0),
        "rt_callback": RoleSpec(2, "FIFO", 70, 0),
        "mpc_main": RoleSpec(3, "FIFO", 60, 0),
        "arm_driver": RoleSpec(4, "OTHER", 0, 0),
        "hand_driver": RoleSpec(4, "OTHER", 0, 0),
        "nrt_callback": RoleSpec(5, "OTHER", 0, 0),
        "nrt_publish": RoleSpec(5, "OTHER", 0, 0),
        "nrt_logging": RoleSpec(5, "OTHER", 0, -5),
        "sim_thread": RoleSpec(-1, "OTHER", 0, 0),
        "viewer": RoleSpec(-1, "OTHER", 0, 0),
    },
    8: {
        "rt_control": RoleSpec(1, "FIFO", 90, 0),
        "rt_callback": RoleSpec(2, "FIFO", 70, 0),
        "mpc_main": RoleSpec(3, "FIFO", 60, 0),
        "arm_driver": RoleSpec(4, "OTHER", 0, 0),
        "hand_driver": RoleSpec(5, "OTHER", 0, 0),
        "nrt_callback": RoleSpec(7, "OTHER", 0, 0),
        "nrt_publish": RoleSpec(7, "OTHER", 0, 0),
        "nrt_logging": RoleSpec(6, "OTHER", 0, -5),
        "sim_thread": RoleSpec(-1, "OTHER", 0, 0),
        "viewer": RoleSpec(-1, "OTHER", 0, 0),
    },
    10: {
        "rt_control": RoleSpec(1, "FIFO", 90, 0),
        "rt_callback": RoleSpec(2, "FIFO", 70, 0),
        "mpc_main": RoleSpec(3, "FIFO", 60, 0),
        "mpc_worker_0": RoleSpec(4, "FIFO", 55, 0),
        "arm_driver": RoleSpec(5, "OTHER", 0, 0),
        "hand_driver": RoleSpec(6, "OTHER", 0, 0),
        "nrt_callback": RoleSpec(8, "OTHER", 0, 0),
        "nrt_publish": RoleSpec(8, "OTHER", 0, 0),
        "nrt_logging": RoleSpec(7, "OTHER", 0, -5),
        "sim_thread": RoleSpec(-1, "OTHER", 0, 0),
        "viewer": RoleSpec(-1, "OTHER", 0, 0),
    },
    12: {
        "rt_control": RoleSpec(1, "FIFO", 90, 0),
        "rt_callback": RoleSpec(2, "FIFO", 70, 0),
        "mpc_main": RoleSpec(3, "FIFO", 60, 0),
        "mpc_worker_0": RoleSpec(4, "FIFO", 55, 0),
        "mpc_worker_1": RoleSpec(5, "FIFO", 55, 0),
        "arm_driver": RoleSpec(6, "OTHER", 0, 0),
        "hand_driver": RoleSpec(7, "OTHER", 0, 0),
        "nrt_callback": RoleSpec(9, "OTHER", 0, 0),
        "nrt_publish": RoleSpec(9, "OTHER", 0, 0),
        "nrt_logging": RoleSpec(8, "OTHER", 0, -5),
        "sim_thread": RoleSpec(-1, "OTHER", 0, 0),
        "viewer": RoleSpec(-1, "OTHER", 0, 0),
    },
    14: {
        "rt_control": RoleSpec(1, "FIFO", 90, 0),
        "rt_callback": RoleSpec(2, "FIFO", 70, 0),
        "mpc_main": RoleSpec(3, "FIFO", 60, 0),
        "mpc_worker_0": RoleSpec(4, "FIFO", 55, 0),
        "mpc_worker_1": RoleSpec(5, "FIFO", 55, 0),
        "arm_driver": RoleSpec(6, "OTHER", 0, 0),
        "hand_driver": RoleSpec(7, "OTHER", 0, 0),
        "nrt_callback": RoleSpec(9, "OTHER", 0, 0),
        "nrt_publish": RoleSpec(9, "OTHER", 0, 0),
        "nrt_logging": RoleSpec(8, "OTHER", 0, -5),
        "sim_thread": RoleSpec(-1, "OTHER", 0, 0),
        "viewer": RoleSpec(-1, "OTHER", 0, 0),
    },
    16: {
        "rt_control": RoleSpec(1, "FIFO", 90, 0),
        "rt_callback": RoleSpec(2, "FIFO", 70, 0),
        "mpc_main": RoleSpec(3, "FIFO", 60, 0),
        "mpc_worker_0": RoleSpec(4, "FIFO", 55, 0),
        "mpc_worker_1": RoleSpec(5, "FIFO", 55, 0),
        "arm_driver": RoleSpec(6, "OTHER", 0, 0),
        "hand_driver": RoleSpec(7, "OTHER", 0, 0),
        "nrt_callback": RoleSpec(9, "OTHER", 0, 0),
        "nrt_publish": RoleSpec(9, "OTHER", 0, 0),
        "nrt_logging": RoleSpec(8, "OTHER", 0, -5),
        "sim_thread": RoleSpec(-1, "OTHER", 0, 0),
        "viewer": RoleSpec(-1, "OTHER", 0, 0),
    },
}


def tier_for_cores(physical_cores: int) -> int:
    """Return the tier id used for ``physical_cores`` physical cores."""
    for threshold, tier_id in TIER_THRESHOLDS:
        if physical_cores >= threshold:
            return tier_id
    return FALLBACK_TIER


def role_spec(role: str, physical_cores: int) -> RoleSpec | None:
    """Placement of ``role`` at ``physical_cores``; ``None`` if absent there."""
    return ROLE_SPECS[tier_for_cores(physical_cores)].get(role)
