#!/usr/bin/env python3
"""Generate every executable encoding of the RTC thread/CPU layout.

Single source of truth: ``repo_scripts/config/thread_layout.yaml`` (issue #153 M1).

Before M1 the tier -> slot assignment was re-encoded by hand in six places::

    rtc_base/.../thread_utils.hpp::SelectThreadConfigs + thread_config.hpp
    repo_scripts/scripts/lib/rt_common.sh::get_mpc_cores
    repo_scripts/scripts/lib/rt_common.sh::get_rt_cores
    repo_scripts/scripts/lib/rt_common.sh::get_nrt_cores
    repo_scripts/scripts/verify_rt_runtime.sh::build_expected_threads
    rtc_tools/rtc_tools/launch/thread_layout.py

Five of the six had no direct unit test, so a tier edit could land in one and
silently skip the rest.  Now all of them are generated from the manifest and
``--check`` is the drift gate (CI + ``colcon test``).

Usage::

    python3 repo_scripts/scripts/gen_thread_layout.py            # --check
    python3 repo_scripts/scripts/gen_thread_layout.py --write
    python3 repo_scripts/scripts/gen_thread_layout.py --self-test

``--check`` compares byte-for-byte, so it catches both a stale artifact (someone
edited the manifest and forgot to regenerate) and a hand-edited artifact.  The
C++ header is compared *after* clang-format, so that one axis does need the
formatter -- resolved exactly the way ``.claude/hooks/format-code.sh`` resolves
it (system binary first, then the pinned release through ``uvx``), because that
hook keeps rewriting the header on boxes where the system binary is missing.  If
no candidate exists at all the header is reported as skipped rather than falsely
stale, and CI installs clang-format so all five artifacts stay in scope there.
"""

from __future__ import annotations

import argparse
import os
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path

import yaml

REPO_ROOT = Path(__file__).resolve().parents[2]
MANIFEST = REPO_ROOT / "repo_scripts" / "config" / "thread_layout.yaml"

GENERATED_BANNER_LINES = (
    "AUTO-GENERATED by repo_scripts/scripts/gen_thread_layout.py -- DO NOT EDIT.",
    "Source of truth: repo_scripts/config/thread_layout.yaml",
    "Regenerate:      python3 repo_scripts/scripts/gen_thread_layout.py --write",
    "Drift gate:      python3 repo_scripts/scripts/gen_thread_layout.py --check",
)

# Keep generated comments inside .clang-format's ColumnLimit: clang-format
# reflows longer comment lines and its reflow merges adjacent rows together.
_CPP_COLUMN_LIMIT = 100

_POLICY_CPP = {"FIFO": "SCHED_FIFO", "RR": "SCHED_RR", "OTHER": "SCHED_OTHER"}
# verify_rt_runtime.sh's expected-thread spec encodes the policy as 1/0.
_POLICY_VERIFIER = {"FIFO": 1, "RR": 1, "OTHER": 0}


# ── Manifest model ──────────────────────────────────────────────────────────


@dataclass(frozen=True)
class Spec:
    """One role's placement on one tier."""

    slot: int
    policy: str
    priority: int
    nice: int

    @property
    def policy_cpp(self) -> str:
        return _POLICY_CPP[self.policy]

    @property
    def policy_verifier(self) -> int:
        return _POLICY_VERIFIER[self.policy]

    @property
    def policy_shell(self) -> str:
        return _POLICY_CPP[self.policy]


@dataclass(frozen=True)
class Tier:
    id: int
    min_cores: int
    label: str
    cpp_suffix: str
    cpp_suffix_mpc: str
    notes: tuple[str, ...]
    specs: dict[str, Spec]  # role key -> spec (mpc_worker_N included)
    num_workers: int


@dataclass(frozen=True)
class Manifest:
    layout_version: str
    os_slot: int
    roles: list[dict]
    tiers: list[Tier]  # ascending min_cores
    verifier_order: tuple[str, ...]
    max_workers: int
    outputs: dict[str, str]
    doc_blocks: list[dict]
    doc: dict

    # ── convenience ────────────────────────────────────────────────────
    @property
    def tiers_desc(self) -> list[Tier]:
        """Tiers in dispatch order (highest min_cores first)."""
        return sorted(self.tiers, key=lambda t: t.min_cores, reverse=True)

    def tier_for(self, ncpu: int) -> Tier:
        for tier in self.tiers_desc:
            if ncpu >= tier.min_cores:
                return tier
        return self.tiers[0]

    def tier_range(self, tier: Tier) -> tuple[int, int | None]:
        """(low, high) physical-core range covered by ``tier``; high None = open."""
        higher = [t.min_cores for t in self.tiers if t.min_cores > tier.min_cores]
        return tier.min_cores, (min(higher) - 1 if higher else None)

    def role(self, key: str) -> dict:
        for entry in self.roles:
            if entry["key"] == key:
                return entry
        raise KeyError(key)

    def role_note(self, key: str) -> str:
        """``map_note`` for a concrete role key, or "" — mpc sub-roles have none."""
        for entry in self.roles:
            if entry.get("kind") != "mpc" and entry["key"] == key:
                note = entry.get("map_note")
                return f" -- {note}" if note else ""
        return ""


def _spec(raw: dict) -> Spec:
    return Spec(
        slot=int(raw["slot"]),
        policy=str(raw["policy"]),
        priority=int(raw["priority"]),
        nice=int(raw["nice"]),
    )


def load_manifest(path: Path = MANIFEST) -> Manifest:
    data = yaml.safe_load(path.read_text(encoding="utf-8"))

    roles = data["roles"]
    mpc_role = next(r for r in roles if r.get("kind") == "mpc")
    max_workers = int(mpc_role["max_workers"])

    tiers: list[Tier] = []
    for raw_tier in data["tiers"]:
        raw_roles = dict(raw_tier["roles"])
        workers = raw_roles.pop("mpc_workers", []) or []
        if len(workers) > max_workers:
            raise ValueError(
                f"tier {raw_tier['id']}: {len(workers)} workers exceeds max_workers={max_workers}"
            )
        specs = {key: _spec(value) for key, value in raw_roles.items()}
        for index, worker in enumerate(workers):
            specs[f"{mpc_role['worker']['key_prefix']}{index}"] = _spec(worker)
        cpp_suffix = str(raw_tier.get("cpp_suffix", ""))
        tiers.append(
            Tier(
                id=int(raw_tier["id"]),
                min_cores=int(raw_tier["min_cores"]),
                label=str(raw_tier["label"]),
                cpp_suffix=cpp_suffix,
                cpp_suffix_mpc=str(raw_tier.get("cpp_suffix_mpc", cpp_suffix)),
                notes=tuple(raw_tier.get("notes", ())),
                specs=specs,
                num_workers=len(workers),
            )
        )
    tiers.sort(key=lambda t: t.min_cores)

    # `in_controller_process` declares which roles verify_rt_runtime.sh may hunt
    # for inside the controller process, but nothing consumed it: verifier_order
    # alone drove the generated table.  Listing an external process there
    # (arm/hand/sim/viewer) emits a row the verifier can never match and WARNs
    # forever on a healthy box -- issue #353 verbatim, which the comment above
    # verifier_order claims to prevent.  The reverse hole is worse: dropping an
    # in-process thread from verifier_order removes it from the expected table
    # with no other signal.  Enforce the two sides against each other.
    verifier_order = tuple(data["verifier_order"])
    in_process: list[str] = []
    for entry in roles:
        if entry.get("kind") == "mpc":
            if entry["main"].get("in_controller_process"):
                in_process.append(str(entry["main"]["key"]))
            if entry["worker"].get("in_controller_process"):
                in_process.extend(
                    f"{entry['worker']['key_prefix']}{index}" for index in range(max_workers)
                )
        elif entry.get("in_controller_process"):
            in_process.append(str(entry["key"]))
    if set(verifier_order) != set(in_process):
        missing = sorted(set(in_process) - set(verifier_order)) or ["-"]
        extra = sorted(set(verifier_order) - set(in_process)) or ["-"]
        raise SystemExit(
            f"{path.relative_to(REPO_ROOT)}: verifier_order must list exactly the roles "
            "carrying in_controller_process: true.\n"
            f"  in-process but unverified: {', '.join(missing)}\n"
            f"  listed but not in-process (would false-WARN, #353): {', '.join(extra)}"
        )

    return Manifest(
        layout_version=str(data["layout_version"]),
        os_slot=int(data["os_slot"]),
        roles=roles,
        tiers=tiers,
        verifier_order=verifier_order,
        max_workers=max_workers,
        outputs=dict(data["outputs"]),
        doc_blocks=list(data.get("doc_blocks", [])),
        doc=dict(data.get("doc", {})),
    )


# ── shared helpers ──────────────────────────────────────────────────────────


def _thread_role_keys(m: Manifest) -> list[str]:
    """Every concrete placeable role key, in manifest declaration order."""
    keys: list[str] = []
    for entry in m.roles:
        if entry.get("kind") == "mpc":
            keys.append(entry["main"]["key"])
            keys.extend(f"{entry['worker']['key_prefix']}{i}" for i in range(m.max_workers))
        else:
            keys.append(entry["key"])
    return keys


def _thread_name(m: Manifest, key: str) -> str:
    for entry in m.roles:
        if entry.get("kind") == "mpc":
            if entry["main"]["key"] == key:
                return str(entry["main"]["thread_name"])
            prefix = entry["worker"]["key_prefix"]
            if key.startswith(prefix):
                return f"{entry['worker']['thread_name_prefix']}{key[len(prefix) :]}"
        elif entry["key"] == key:
            return str(entry["thread_name"])
    raise KeyError(key)


def _verifier_optional(m: Manifest, key: str) -> bool:
    mpc = next(r for r in m.roles if r.get("kind") == "mpc")
    return key.startswith(mpc["worker"]["key_prefix"]) and bool(
        mpc["worker"].get("verifier_optional")
    )


def _csv(values: list[int]) -> str:
    return ",".join(str(v) for v in values)


def mpc_cores(m: Manifest, tier: Tier) -> list[int]:
    keys = ["mpc_main"] + [f"mpc_worker_{i}" for i in range(tier.num_workers)]
    return [tier.specs[k].slot for k in keys]


def rt_cores(m: Manifest, tier: Tier) -> list[int]:
    return [tier.specs["rt_control"].slot, tier.specs["rt_callback"].slot] + mpc_cores(m, tier)


def nrt_cores(m: Manifest, tier: Tier) -> list[int]:
    slots = {tier.specs["nrt_logging"].slot, tier.specs["nrt_callback"].slot}
    return sorted(slots)


# ── C++ emitter ─────────────────────────────────────────────────────────────


def _cpp_symbol(m: Manifest, role_key: str, tier: Tier) -> str:
    entry = m.role(role_key)
    suffix = tier.cpp_suffix_mpc if entry.get("kind") == "mpc" else tier.cpp_suffix
    return f"k{entry['cpp_symbol']}{suffix}"


def _cpp_thread_config(spec: Spec, name: str, indent: str, *, brace_prefix: str) -> list[str]:
    """clang-format-stable designated-initializer block."""
    pad = " " * len(brace_prefix)
    return [
        f"{indent}{brace_prefix}.cpu_core = {spec.slot},",
        f"{indent}{pad}.sched_policy = {spec.policy_cpp},",
        f"{indent}{pad}.sched_priority = {spec.priority},",
        f"{indent}{pad}.nice_value = {spec.nice},",
        f'{indent}{pad}.name = "{name}"}};',
    ]


def _sched_label(spec: Spec) -> str:
    return f"CFS {spec.nice}" if spec.policy == "OTHER" else f"{spec.policy} {spec.priority}"


def _cpp_role_notes(m: Manifest) -> list[str]:
    """Tier-invariant role annotations, emitted once instead of on every slot."""
    notes = [(entry["key"], entry["map_note"]) for entry in m.roles if entry.get("map_note")]
    if not notes:
        return []
    width = max(len(key) for key, _ in notes)
    lines = ["// Role notes (tier-invariant):"]
    lines += [f"//   {key.ljust(width)}  {note}" for key, note in notes]
    return lines


def _cpp_core_map(m: Manifest, tier: Tier) -> list[str]:
    """Derived slot -> role comment map. Never hand-written, so it cannot drift."""
    occupancy: dict[int, list[str]] = {}
    for key in _thread_role_keys(m):
        spec = tier.specs.get(key)
        if spec is None or spec.slot < 0:
            continue
        occupancy.setdefault(spec.slot, []).append(key)

    # The tier id IS its slot count: the "12-core configuration" describes slots
    # 0-11, of which the ones no role claims are spare.
    width = max(tier.id, max(occupancy, default=0) + 1)

    lines = [f"// ── {tier.label} (layout {m.layout_version}) ──"]
    for slot in range(width):
        parts = ["OS / DDS / IRQ"] if slot == m.os_slot else []
        parts += [
            f"{_thread_name(m, key)} ({_sched_label(tier.specs[key])})"
            for key in occupancy.get(slot, [])
        ]
        # Wrap below ColumnLimit ourselves: clang-format reflows any comment
        # line that exceeds it, and its reflow merges the slot rows together.
        head, cont = f"//   Slot {slot}: ", "//            "
        line = head
        for index, part in enumerate(parts or ["spare"]):
            piece = part if index == 0 else f" + {part}"
            if len(line) + len(piece) > _CPP_COLUMN_LIMIT and line not in (head, cont):
                lines.append(line)
                line = cont + f"+ {part}"
            else:
                line += piece
        lines.append(line)

    unpinned = [
        _thread_name(m, k)
        for k in _thread_role_keys(m)
        if tier.specs.get(k) is not None and tier.specs[k].slot < 0
    ]
    if unpinned:
        lines.append(f"//   unpinned (cpu_core = -1): {', '.join(unpinned)}")
    lines += [f"// {note}" for note in tier.notes]
    return lines


def emit_cpp(m: Manifest) -> str:
    out: list[str] = []
    for line in GENERATED_BANNER_LINES:
        out.append(f"// {line}")
    out.append("//")
    out.append("// Tier constants + the pure tier dispatch. The hand-written prose, the")
    out.append("// ThreadConfig / MpcThreadConfig / SystemThreadConfigs definitions and the")
    out.append("// layout rationale all stay in thread_config.hpp, which includes this file.")
    role_notes = _cpp_role_notes(m)
    if role_notes:
        out.append("//")
        out.extend(role_notes)
    out.append("#ifndef RTC_BASE_THREAD_CONFIG_GENERATED_HPP_")
    out.append("#define RTC_BASE_THREAD_CONFIG_GENERATED_HPP_")
    out.append("")
    out.append('#include "rtc_base/threading/thread_config.hpp"')
    out.append("")
    out.append("#include <sched.h>  // SCHED_FIFO, SCHED_OTHER, SCHED_RR")
    out.append("")
    out.append("namespace rtc {")
    out.append("")
    out.append("// kMpcMaxWorkers sizes MpcThreadConfig::workers and is hand-written in")
    out.append("// thread_config.hpp (it has to precede the struct that uses it, so it cannot")
    out.append("// come from this file). The manifest declares the same number; without this")
    out.append("// assert, lowering max_workers below it silently over-allocates the array.")
    out.append(
        f"static_assert(kMpcMaxWorkers == {m.max_workers},"
        ' "kMpcMaxWorkers must match max_workers in thread_layout.yaml");'
    )

    for tier in m.tiers:
        out.append("")
        out.extend(_cpp_core_map(m, tier))
        out.append("")
        for entry in m.roles:
            if entry.get("kind") == "mpc":
                symbol = _cpp_symbol(m, entry["key"], tier)
                main = tier.specs["mpc_main"]
                out.append(f"inline const MpcThreadConfig {symbol}{{")
                out.append("    .main =")
                out.append("        ThreadConfig{")
                out.append(f"            .cpu_core = {main.slot},")
                out.append(f"            .sched_policy = {main.policy_cpp},")
                out.append(f"            .sched_priority = {main.priority},")
                out.append(f"            .nice_value = {main.nice},")
                out.append(f'            .name = "{_thread_name(m, "mpc_main")}",')
                out.append("        },")
                out.append(f"    .num_workers = {tier.num_workers},")
                if tier.num_workers == 0:
                    out.append("    .workers = {},")
                else:
                    out.append("    .workers =")
                    out.append("        {")
                    for index in range(m.max_workers):
                        key = f"mpc_worker_{index}"
                        spec = tier.specs.get(key)
                        if spec is None:
                            out.append("            ThreadConfig{},")
                            continue
                        out.append("            ThreadConfig{")
                        out.append(f"                .cpu_core = {spec.slot},")
                        out.append(f"                .sched_policy = {spec.policy_cpp},")
                        out.append(f"                .sched_priority = {spec.priority},")
                        out.append(f"                .nice_value = {spec.nice},")
                        out.append(f'                .name = "{_thread_name(m, key)}",')
                        out.append("            },")
                    out.append("        },")
                out.append("};")
            else:
                key = entry["key"]
                spec = tier.specs[key]
                symbol = _cpp_symbol(m, key, tier)
                prefix = f"inline const ThreadConfig {symbol}{{"
                out.extend(_cpp_thread_config(spec, _thread_name(m, key), "", brace_prefix=prefix))
            out.append("")
        out.pop()  # trailing blank inside the tier block

    out.append("")
    out.append("// Pure tier dispatch. SelectThreadConfigs() in thread_utils.hpp is the")
    out.append("// runtime-probing wrapper; this overload takes the core count explicitly so")
    out.append("// tests can sweep tiers the host machine does not have.")
    out.append("inline SystemThreadConfigs SelectThreadConfigsForCoreCount(int ncpu) noexcept {")
    # SystemThreadConfigs' member order. Eight of its nine members share the
    # ThreadConfig type, so a positional aggregate init still compiled with the
    # roles permuted and every thread silently took its neighbour's slot and
    # priority. The emitted designated initializers make that a compile error
    # (C++20 requires them in declaration order); the set check below closes the
    # other half -- a manifest role that never reaches the struct at all.
    field_order = [
        "rt_control",
        "rt_callback",
        "nrt_logging",
        "nrt_callback",
        "arm_driver",
        "hand_driver",
        "sim_thread",
        "viewer",
        "mpc",
    ]
    declared_roles = {str(entry["key"]) for entry in m.roles}
    if set(field_order) != declared_roles:
        missing = sorted(declared_roles - set(field_order)) or ["-"]
        extra = sorted(set(field_order) - declared_roles) or ["-"]
        raise SystemExit(
            "gen_thread_layout.py: field_order and the manifest's roles disagree; "
            "SelectThreadConfigsForCoreCount() would leave a member default-initialised.\n"
            f"  in the manifest, not emitted: {', '.join(missing)}\n"
            f"  emitted, not in the manifest: {', '.join(extra)}"
        )
    tiers_desc = m.tiers_desc
    for index, tier in enumerate(tiers_desc):
        body = ", ".join(f".{key} = {_cpp_symbol(m, key, tier)}" for key in field_order)
        if index == len(tiers_desc) - 1:
            out.append(f"  return {{{body}}};")
        else:
            out.append(f"  if (ncpu >= {tier.min_cores}) {{")
            out.append(f"    return {{{body}}};")
            out.append("  }")
    out.append("}")
    out.append("")
    out.append("}  // namespace rtc")
    out.append("")
    out.append("#endif  // RTC_BASE_THREAD_CONFIG_GENERATED_HPP_")
    return "\n".join(out) + "\n"


# ── shell emitter ───────────────────────────────────────────────────────────


def emit_shell(m: Manifest) -> str:
    out: list[str] = ["#!/usr/bin/env bash"]
    for line in GENERATED_BANNER_LINES:
        out.append(f"# {line}")
    out += [
        "#",
        "# Sourced by repo_scripts/scripts/lib/rt_common.sh. Everything here is a pure",
        "# function of the physical core count -- no sysfs, no build artifacts -- so",
        "# install.sh can source it before the workspace is built (bootstrap order).",
        "#",
        "# Every slot below is a ThreadConfig::cpu_core *slot index*, NOT a kernel",
        "# logical CPU id. Run it through slot_to_logical_cpu() before comparing",
        "# against a /proc affinity mask.",
        "# shellcheck shell=bash",
        "",
        f'RTC_THREAD_LAYOUT_VERSION="{m.layout_version}"',
        "",
        "# Tier id for a physical core count. Mirrors",
        "# SelectThreadConfigsForCoreCount() in thread_config_generated.hpp.",
        "_rtc_layout_tier() {",
        '  local ncpu="$1"',
    ]
    tiers_desc = m.tiers_desc
    for index, tier in enumerate(tiers_desc):
        if index == len(tiers_desc) - 1:
            out.append("  else")
            out.append(f"    echo {tier.id}")
        elif index == 0:
            out.append(f'  if [[ "$ncpu" -ge {tier.min_cores} ]]; then')
            out.append(f"    echo {tier.id}")
        else:
            out.append(f'  elif [[ "$ncpu" -ge {tier.min_cores} ]]; then')
            out.append(f"    echo {tier.id}")
    out += ["  fi", "}", ""]

    # ── generic per-role lookup ────────────────────────────────────────
    out += [
        '# get_role_spec <role> [ncpu] -> "<slot> <policy> <priority> <nice>"',
        "# Returns non-zero for a role that does not exist on the tier (e.g. an",
        "# mpc_worker below the 10-core tier).",
        "get_role_spec() {",
        '  local role="$1"',
        '  local ncpu="${2:-$(get_physical_cores)}"',
        "  local tier",
        '  tier=$(_rtc_layout_tier "$ncpu")',
        '  case "${tier}|${role}" in',
    ]
    for tier in m.tiers:
        for key in _thread_role_keys(m):
            spec = tier.specs.get(key)
            if spec is None:
                continue
            arm = f'"{tier.id}|{key}")'
            out.append(
                f'    {arm} echo "{spec.slot} {spec.policy_shell} {spec.priority} {spec.nice}" ;;'
            )
    out += [
        "    *) return 1 ;;",
        "  esac",
        "}",
        "",
        "get_role_slot() {",
        "  local spec",
        '  spec=$(get_role_spec "$@") || return 1',
        '  echo "$spec" | cut -d" " -f1',
        "}",
        "",
        "get_role_policy() {",
        "  local spec",
        '  spec=$(get_role_spec "$@") || return 1',
        '  echo "$spec" | cut -d" " -f2',
        "}",
        "",
        "get_role_priority() {",
        "  local spec",
        '  spec=$(get_role_spec "$@") || return 1',
        '  echo "$spec" | cut -d" " -f3',
        "}",
        "",
        "get_role_nice() {",
        "  local spec",
        '  spec=$(get_role_spec "$@") || return 1',
        '  echo "$spec" | cut -d" " -f4',
        "}",
        "",
    ]

    def _tier_case(name: str, doc: list[str], value_of, arg_doc: str = "[ncpu]") -> list[str]:
        block = [f"# {line}" for line in doc]
        block += [
            f"{name}() {{",
            '  local ncpu="${1:-$(get_physical_cores)}"',
            "  local tier",
            '  tier=$(_rtc_layout_tier "$ncpu")',
            '  case "$tier" in',
        ]
        for tier in m.tiers:
            block.append(f'    {tier.id}) echo "{value_of(tier)}" ;;')
        block += ["  esac", "}", ""]
        return block

    out += _tier_case(
        "get_mpc_cores",
        [
            "MPC slots (main first, then workers) as CSV. $1 overrides the detected",
            "physical core count so print_thread_layout and the tests can render a",
            "tier this machine does not have.",
        ],
        lambda t: _csv(mpc_cores(m, t)),
    )
    out += _tier_case(
        "get_rt_cores",
        [
            "RT group slots: rt_control + rt_callback + MPC (main + workers).",
            "Base for get_rt_cores_with_siblings() / get_cm_shield_cpus().",
        ],
        lambda t: _csv(rt_cores(m, t)),
    )
    out += _tier_case(
        "get_nrt_cores",
        [
            "nrt_logging + nrt_callback slots, deduplicated and ascending. On the",
            "degraded tier both share the OS slot -- callers that shield must drop",
            "the OS slot (get_cm_shield_cpus does), never widen onto it.",
        ],
        lambda t: _csv(nrt_cores(m, t)),
    )
    out += _tier_case(
        "get_arm_driver_slot",
        ["Slot the external arm driver process belongs on (launch taskset target)."],
        lambda t: t.specs["arm_driver"].slot,
    )
    out += _tier_case(
        "get_hand_driver_slot",
        ["Slot the external hand driver process belongs on (in-process self-pin, #345)."],
        lambda t: t.specs["hand_driver"].slot,
    )

    out += [
        "# OS / DDS / NIC IRQ slot. Never shielded, never an RT pin target.",
        "get_os_cores() {",
        f'  echo "{m.os_slot}"',
        "}",
        "",
        "# Expected in-process controller threads for verify_rt_runtime.sh, one",
        '# "name:slot:policy:priority[:optional]" per line. policy: 1=SCHED_FIFO,',
        '# 0=SCHED_OTHER. "optional" means a missing thread is SKIP, not WARN.',
        "rtc_expected_threads() {",
        '  local ncpu="${1:-$(get_physical_cores)}"',
        "  local tier",
        '  tier=$(_rtc_layout_tier "$ncpu")',
        '  case "$tier" in',
    ]
    for tier in m.tiers:
        out.append(f"    {tier.id})")
        for key in m.verifier_order:
            spec = tier.specs.get(key)
            if spec is None:
                continue
            row = f"{_thread_name(m, key)}:{spec.slot}:{spec.policy_verifier}:{spec.priority}"
            if _verifier_optional(m, key):
                row += ":optional"
            out.append(f'      echo "{row}"')
        out.append("      ;;")
    out += ["  esac", "}", ""]
    return "\n".join(out) + "\n"


# ── Python emitter ──────────────────────────────────────────────────────────


def emit_python(m: Manifest) -> str:
    out: list[str] = ['"""' + GENERATED_BANNER_LINES[0]]
    for line in GENERATED_BANNER_LINES[1:]:
        out.append(line)
    out += [
        "",
        "Full per-tier role table mirrored for launch-time ``taskset`` pinning.",
        "``rtc_tools.launch.thread_layout`` is the hand-written adapter that exposes",
        "the stable public API on top of this table.",
        "",
        "Every ``slot`` is a ThreadConfig::cpu_core *slot index*, not a kernel logical",
        'CPU id; ``-1`` means "do not pin".',
        '"""',
        "",
        "from __future__ import annotations",
        "",
        "from typing import NamedTuple",
        "",
        "",
        "class RoleSpec(NamedTuple):",
        '    """One role\'s placement on one tier."""',
        "",
        "    slot: int",
        "    policy: str",
        "    priority: int",
        "    nice: int",
        "",
        "",
        f'LAYOUT_VERSION = "{m.layout_version}"',
        f"OS_SLOT = {m.os_slot}",
        f"MAX_WORKERS = {m.max_workers}",
        "",
        "# Dispatch order: the first tier whose threshold is met wins; the last entry",
        "# is the fallback used below every threshold.",
        "TIER_THRESHOLDS: tuple[tuple[int, int], ...] = (",
    ]
    tiers_desc = m.tiers_desc
    for tier in tiers_desc[:-1]:
        out.append(f"    ({tier.min_cores}, {tier.id}),")
    out += [
        ")",
        f"FALLBACK_TIER = {tiers_desc[-1].id}",
        "",
        "ROLE_SPECS: dict[int, dict[str, RoleSpec]] = {",
    ]
    for tier in m.tiers:
        out.append(f"    {tier.id}: {{")
        for key in _thread_role_keys(m):
            spec = tier.specs.get(key)
            if spec is None:
                continue
            out.append(
                f'        "{key}": RoleSpec({spec.slot}, "{spec.policy}", '
                f"{spec.priority}, {spec.nice}),"
            )
        out.append("    },")
    out += [
        "}",
        "",
        "",
        "def tier_for_cores(physical_cores: int) -> int:",
        '    """Return the tier id used for ``physical_cores`` physical cores."""',
        "    for threshold, tier_id in TIER_THRESHOLDS:",
        "        if physical_cores >= threshold:",
        "            return tier_id",
        "    return FALLBACK_TIER",
        "",
        "",
        "def role_spec(role: str, physical_cores: int) -> RoleSpec | None:",
        '    """Placement of ``role`` at ``physical_cores``; ``None`` if absent there."""',
        "    return ROLE_SPECS[tier_for_cores(physical_cores)].get(role)",
    ]
    return "\n".join(out) + "\n"


# ── documentation blocks ────────────────────────────────────────────────────


def _tier_range_label(m: Manifest, tier: Tier) -> str:
    low, high = m.tier_range(tier)
    if tier is m.tiers[0]:
        return f"≤{high}" if high is not None else f"{low}+"
    if high is None:
        return f"{low}+"
    return f"{low}–{high}"


def emit_doc_matrix(m: Manifest) -> str:
    """rtc_base/README.md — role × tier slot matrix."""
    doc = m.doc
    header_suffix = {int(k): v for k, v in doc.get("tier_header_suffixes", {}).items()}
    label_suffix = doc.get("role_label_suffixes", {})
    cell_suffix = doc.get("cell_suffixes", {})
    unpinned = doc.get("unpinned_cell", "-1")

    headers = ["스레드"] + [f"{t.id}코어{header_suffix.get(t.id, '')}" for t in m.tiers]
    rows = ["| " + " | ".join(headers) + " |"]
    rows.append("|" + "|".join(["--------"] + ["-------"] * len(m.tiers)) + "|")

    for key in _thread_role_keys(m):
        if all(t.specs.get(key) is None for t in m.tiers):
            continue
        ref = next(t.specs[key] for t in reversed(m.tiers) if t.specs.get(key) is not None)
        if ref.policy == "OTHER":
            sched = f"CFS {ref.nice}"
        else:
            sched = f"{ref.policy} {ref.priority}"
        label = f"**{_thread_name(m, key)}** ({sched}{label_suffix.get(key, '')})"
        cells = []
        for tier in m.tiers:
            spec = tier.specs.get(key)
            if spec is None:
                cells.append("—")
            elif spec.slot < 0:
                cells.append(unpinned)
            else:
                cells.append(f"Core {spec.slot}{cell_suffix.get(f'{tier.id}|{key}', '')}")
        rows.append("| " + " | ".join([label] + cells) + " |")
    return "\n".join(rows)


def emit_doc_tiers(m: Manifest) -> str:
    """repo_scripts/README.md — per-tier helper outputs."""
    rows = [
        "| tier (물리 코어) | `get_rt_cores()` | `get_mpc_cores()` | `get_nrt_cores()`"
        " | `get_os_cores()` | arm / hand slot |",
        "|---|---|---|---|---|---|",
    ]
    for tier in m.tiers:
        rows.append(
            "| {label} | `{rt}` | `{mpc}` | `{nrt}` | `{os}` | {arm} / {hand} |".format(
                label=_tier_range_label(m, tier),
                rt=_csv(rt_cores(m, tier)),
                mpc=_csv(mpc_cores(m, tier)),
                nrt=_csv(nrt_cores(m, tier)),
                os=m.os_slot,
                arm=tier.specs["arm_driver"].slot,
                hand=tier.specs["hand_driver"].slot,
            )
        )
    return "\n".join(rows)


_DOC_EMITTERS = {
    "thread-layout-matrix": emit_doc_matrix,
    "thread-layout-tiers": emit_doc_tiers,
}


def _begin(block: str) -> str:
    return f"<!-- BEGIN GENERATED: {block} -->"


def _end(block: str) -> str:
    return f"<!-- END GENERATED: {block} -->"


def render_doc(m: Manifest, path: Path, block: str, text: str | None = None) -> str:
    """Return ``path``'s content with ``block`` refreshed from the manifest.

    ``text`` carries the result of an earlier block in the same file; without it
    a second block would be rendered against the on-disk text and the first
    block's refresh would be dropped on the floor.
    """
    if text is None:
        text = path.read_text(encoding="utf-8")
    begin, end = _begin(block), _end(block)
    if begin not in text or end not in text:
        raise SystemExit(
            f"{path.relative_to(REPO_ROOT)}: missing marker pair for block '{block}'.\n"
            f"  Wrap the table with:\n    {begin}\n    ...\n    {end}"
        )
    head, rest = text.split(begin, 1)
    _, tail = rest.split(end, 1)
    body = _DOC_EMITTERS[block](m)
    note = (
        "<!-- Generated from repo_scripts/config/thread_layout.yaml by"
        " repo_scripts/scripts/gen_thread_layout.py. Do not edit by hand. -->"
    )
    return f"{head}{begin}\n{note}\n\n{body}\n\n{end}{tail}"


# ── driver ──────────────────────────────────────────────────────────────────


def build_targets(m: Manifest) -> tuple[dict[Path, str], list[str]]:
    """Return ``{path: expected content}`` plus the artifacts that had to be skipped.

    The C++ artifact is piped through clang-format so the checked-in file is
    byte-identical to what the repo's PostToolUse format hook would produce --
    otherwise the first person to open the header would make ``--check`` fail.
    That makes clang-format a prerequisite for emitting C++: when it is missing
    the artifact is reported as skipped rather than compared against unformatted
    text (a false STALE). Its values stay covered by the compiler and by
    rtc_base/test/test_mpc_thread_config.cpp.
    """
    skipped: list[str] = []
    targets: dict[Path, str] = {
        REPO_ROOT / m.outputs["shell"]: emit_shell(m),
        REPO_ROOT / m.outputs["python"]: emit_python(m),
    }
    cpp_path = REPO_ROOT / m.outputs["cpp"]
    formatted = _clang_format(emit_cpp(m), cpp_path)
    if formatted is None:
        skipped.append(f"{cpp_path.relative_to(REPO_ROOT)} (clang-format unavailable)")
    else:
        targets[cpp_path] = formatted
    for entry in m.doc_blocks:
        path = REPO_ROOT / entry["file"]
        # Chain, never overwrite: two blocks in one file must both survive.
        targets[path] = render_doc(m, path, entry["block"], targets.get(path))
    return targets, skipped


# Formatter lookup mirrors .claude/hooks/format-code.sh. That hook keeps
# reformatting these artifacts on boxes without a system binary -- it falls back
# to the pinned clang-format through uvx and finds ruff inside the workspace
# venv -- so a generator that only consulted PATH would stop gating precisely
# the files the hook keeps rewriting.
_CLANG_FORMAT_PIN = "18.1.8"  # keep in sync with .claude/hooks/format-code.sh


def _clang_format_candidates(path: Path) -> list[list[str]]:
    tail = ["--style=file", f"--assume-filename={path}"]
    return [
        ["clang-format", *tail],
        ["uvx", "--from", f"clang-format=={_CLANG_FORMAT_PIN}", "clang-format", *tail],
    ]


def _ruff_candidates(target: str) -> list[list[str]]:
    tail = ["format", "--stdin-filename", target, "-"]
    candidates: list[list[str]] = []
    venv = os.environ.get("VIRTUAL_ENV")
    if venv:
        candidates.append([str(Path(venv) / "bin" / "ruff"), *tail])
    # <rtc_ws>/.venv, the isolated env install.sh creates beside this checkout.
    candidates.append([str(REPO_ROOT.parents[1] / ".venv" / "bin" / "ruff"), *tail])
    candidates.append(["ruff", *tail])
    return candidates


def _run_formatter(candidates: list[list[str]], text: str) -> tuple[str | None, str | None]:
    """Run the first available formatter; return ``(stdout, error)``.

    ``(None, None)`` means no candidate exists at all -- a skip, not a failure.
    """
    error: str | None = None
    for argv in candidates:
        # uvx may have to download the pinned release on its first run.
        timeout = 120 if argv[0] == "uvx" else 60
        try:
            result = subprocess.run(
                argv, input=text, capture_output=True, text=True, check=False, timeout=timeout
            )
        except FileNotFoundError:
            continue
        except subprocess.TimeoutExpired:
            error = f"{argv[0]} timed out after {timeout}s"
            continue
        if result.returncode == 0:
            return result.stdout, None
        error = f"{argv[0]} failed: {result.stderr.strip()[:200]}"
    return None, error


def _clang_format(text: str, path: Path) -> str | None:
    formatted, _ = _run_formatter(_clang_format_candidates(path), text)
    return formatted


def run_check(m: Manifest) -> int:
    targets, skipped = build_targets(m)
    stale: list[str] = []
    for path, expected in targets.items():
        rel = path.relative_to(REPO_ROOT)
        if not path.exists():
            stale.append(f"  MISSING  {rel}")
        elif path.read_text(encoding="utf-8") != expected:
            stale.append(f"  STALE    {rel}")
    for note in skipped:
        print(f"thread layout: SKIPPED {note}", file=sys.stderr)
    if stale:
        print("thread layout artifacts are out of sync with the manifest:", file=sys.stderr)
        print("\n".join(stale), file=sys.stderr)
        print(
            "\nThe manifest is the single source of truth "
            "(repo_scripts/config/thread_layout.yaml).\n"
            "Do not edit the generated files: run\n"
            "  python3 repo_scripts/scripts/gen_thread_layout.py --write\n"
            "and commit the result alongside the manifest change.",
            file=sys.stderr,
        )
        return 1
    print(f"thread layout: {len(targets)} artifacts in sync with the manifest")
    return 0


def run_write(m: Manifest) -> int:
    targets, skipped = build_targets(m)
    if skipped:
        for note in skipped:
            print(f"cannot generate {note}", file=sys.stderr)
        print(
            "Install clang-format (apt install clang-format, or uv so the pinned "
            f"clang-format=={_CLANG_FORMAT_PIN} can run through uvx) and re-run --write: "
            "emitting unformatted C++ would make --check fail everywhere else.",
            file=sys.stderr,
        )
        return 1
    changed = 0
    for path, expected in targets.items():
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current == expected:
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(expected, encoding="utf-8")
        print(f"wrote {path.relative_to(REPO_ROOT)}")
        changed += 1
    if changed == 0:
        print("thread layout: already up to date")
    return 0


def _formatter_clean(candidates: list[list[str]], text: str, label: str) -> str | None:
    """Run a formatter over ``text``; return its output, or None when unavailable."""
    formatted, error = _run_formatter(candidates, text)
    if formatted is None:
        print(f"  skip  {label}: {error or 'formatter unavailable'}")
    return formatted


def run_self_test(m: Manifest) -> int:
    """Assert the emitters are formatter-idempotent and internally consistent."""
    failures: list[str] = []

    # 1. Every artifact round-trips through --write/--check without change.
    targets, _ = build_targets(m)
    for path, expected in targets.items():
        if path.exists() and path.read_text(encoding="utf-8") != expected:
            failures.append(f"{path.relative_to(REPO_ROOT)} differs from the manifest")

    # 2. The emitted C++ is already clang-format output (build_targets pipes it
    #    through), so a second pass must be a no-op -- otherwise clang-format is
    #    not idempotent here and the format hook could still make --check fail.
    cpp = targets.get(REPO_ROOT / m.outputs["cpp"])
    if cpp is not None:
        formatted = _formatter_clean(
            _clang_format_candidates(REPO_ROOT / m.outputs["cpp"]), cpp, "clang-format"
        )
        if formatted is not None and formatted != cpp:
            failures.append("emit_cpp output is not clang-format stable")

    py = emit_python(m)
    formatted = _formatter_clean(_ruff_candidates(m.outputs["python"]), py, "ruff format")
    if formatted is not None and formatted != py:
        failures.append("emit_python output is not ruff-format stable")

    # 3. Dispatch agrees across the three languages for every sampled core count.
    for ncpu in list(range(1, 18)) + [24, 32, 64]:
        tier = m.tier_for(ncpu)
        if tier.specs["rt_control"].slot < 0:
            failures.append(f"ncpu={ncpu}: rt_control must be pinned")
        rt = rt_cores(m, tier)
        if len(set(rt)) != len(rt):
            failures.append(f"ncpu={ncpu}: RT slots collide: {rt}")

    # 4. Structural invariants the layout must keep on every tier.
    for tier in m.tiers:
        mpc_main = tier.specs["mpc_main"]
        rt_cb = tier.specs["rt_callback"]
        if mpc_main.policy != "OTHER" and mpc_main.priority >= rt_cb.priority:
            failures.append(f"tier {tier.id}: mpc_main priority >= rt_callback")
        for index in range(tier.num_workers):
            worker = tier.specs[f"mpc_worker_{index}"]
            if worker.priority > mpc_main.priority:
                failures.append(f"tier {tier.id}: mpc_worker_{index} priority > mpc_main")
        # arm/hand must not land on an RT controller slot -- the same rule
        # ValidateSystemThreadConfigs() enforces, asserted here because that
        # validator range-checks slots against *this host's* core count, so the
        # C++ test can only reach tiers the host is big enough to represent. A
        # bad slot on the 12/14/16-core tiers would otherwise ship green from
        # every gate and only surface on a deployment box.
        rt_slots = {slot for slot in rt_cores(m, tier) if slot >= 0}
        for role in ("arm_driver", "hand_driver"):
            slot = tier.specs[role].slot
            if slot >= 0 and slot in rt_slots:
                failures.append(
                    f"tier {tier.id}: {role} slot {slot} collides with an RT controller slot"
                )

    if failures:
        print("self-test FAILED:", file=sys.stderr)
        for failure in failures:
            print(f"  - {failure}", file=sys.stderr)
        return 1
    print("self-test passed")
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n", maxsplit=1)[0])
    group = parser.add_mutually_exclusive_group()
    group.add_argument(
        "--check",
        action="store_true",
        help="verify the checked-in artifacts match the manifest (default)",
    )
    group.add_argument("--write", action="store_true", help="regenerate the artifacts")
    group.add_argument(
        "--self-test", action="store_true", help="verify the generator's own invariants"
    )
    args = parser.parse_args(argv)

    manifest = load_manifest()
    if args.write:
        return run_write(manifest)
    if args.self_test:
        return run_self_test(manifest)
    return run_check(manifest)


if __name__ == "__main__":
    sys.exit(main())
